"""Pydantic schemas for full NPC state and situational awareness.

These schemas define the structure returned by NPC creation tools and used
for GM context compilation. They represent the full, rich state of NPCs
including emergent personality, needs, and environmental reactions.
"""

from typing import Literal

from pydantic import BaseModel, Field


# =============================================================================
# Sub-components of NPC State
# =============================================================================


class OccupationDetails(BaseModel):
    """Occupation details generated by LLM.

    When requesting an occupation from the LLM, these details are returned
    to provide setting-appropriate, context-aware occupation information.
    """

    occupation: str = Field(description="Job title, e.g. 'barista', 'starship mechanic'")
    skills: list[str] = Field(
        min_length=1,
        max_length=5,
        description="3-5 relevant skills for this occupation"
    )
    typical_items: list[dict] = Field(
        default_factory=list,
        description="1-3 items they'd typically carry: [{name, description}]"
    )
    education: str | None = Field(
        default=None,
        description="Education/training background for this occupation"
    )
    background_summary: str = Field(
        description="Brief summary of how they came to this occupation"
    )
    wealth_level: str = Field(
        default="modest",
        description="Economic status: destitute, poor, modest, comfortable, wealthy, rich"
    )


class NPCAppearance(BaseModel):
    """Physical appearance with both precise data and narrative descriptions."""

    # Precise data (stored in database)
    age: int = Field(ge=0, le=200, description="Exact age in years")
    gender: str = Field(description="Gender identity")
    height_cm: int = Field(ge=50, le=300, description="Height in centimeters")
    weight_kg: int | None = Field(default=None, ge=10, le=500, description="Weight in kg")
    species: str = Field(default="human", description="Species/race")

    # Narrative descriptions (for GM's prose)
    age_description: str = Field(description="Narrative age, e.g. 'early twenties', 'middle-aged'")
    height_description: str = Field(description="Narrative height, e.g. 'tall', 'average height'")
    build: str = Field(description="Body build, e.g. 'athletic', 'stocky', 'slender'")
    hair: str = Field(description="Hair description, e.g. 'auburn, worn in a practical braid'")
    eyes: str = Field(description="Eye description, e.g. 'bright green', 'dark brown'")
    skin: str = Field(description="Skin description, e.g. 'fair with freckles', 'dark olive'")
    notable_features: list[str] = Field(
        default_factory=list,
        description="Distinctive features: scars, tattoos, birthmarks, etc."
    )
    clothing: str = Field(description="Current clothing description")
    voice: str | None = Field(
        default=None,
        description="Voice description, e.g. 'deep and gravelly', 'soft and melodic'"
    )


class NPCBackground(BaseModel):
    """NPC backstory and history."""

    occupation: str = Field(description="Current occupation/profession")
    occupation_years: int = Field(
        default=1,
        ge=0,
        description="Years in current occupation"
    )
    birthplace: str | None = Field(default=None, description="Where they were born")
    family: str | None = Field(default=None, description="Family situation summary")
    education: str | None = Field(default=None, description="Education/training background")
    hidden_backstory: str | None = Field(
        default=None,
        description="Secret backstory elements (never shown to player)"
    )
    background_summary: str = Field(description="Brief public-facing background summary")


class NPCPersonality(BaseModel):
    """Personality traits, values, and behavioral tendencies."""

    traits: list[str] = Field(
        min_length=2,
        max_length=6,
        description="Core personality traits, e.g. ['shy', 'curious', 'romantic']"
    )
    values: list[str] = Field(
        min_length=1,
        max_length=5,
        description="What they value, e.g. ['honesty', 'family', 'adventure']"
    )
    flaws: list[str] = Field(
        min_length=1,
        max_length=4,
        description="Character flaws, e.g. ['indecisive', 'too trusting']"
    )
    quirks: list[str] = Field(
        default_factory=list,
        max_length=3,
        description="Behavioral quirks, e.g. ['touches hair when nervous']"
    )
    speech_pattern: str | None = Field(
        default=None,
        description="How they speak: accent, vocabulary, speech habits"
    )


class NPCPreferences(BaseModel):
    """NPC preferences, attractions, and aversions."""

    # Gender/age attraction (used for compatibility calculations)
    attracted_to_genders: list[str] = Field(
        default_factory=list,
        description="Genders they find attractive, e.g. ['female'], ['male', 'female']"
    )
    attracted_age_offset: int = Field(
        default=0,
        description="Offset from own age to preferred partner age (e.g., +5 means prefers 5 years older)"
    )

    # Physical/personality attraction preferences
    attracted_to_physical: list[str] = Field(
        default_factory=list,
        description="Physical traits they find attractive"
    )
    attracted_to_personality: list[str] = Field(
        default_factory=list,
        description="Personality traits they find attractive"
    )

    # Food preferences
    favorite_foods: list[str] = Field(
        default_factory=list,
        description="Foods they particularly enjoy"
    )
    disliked_foods: list[str] = Field(
        default_factory=list,
        description="Foods they dislike or avoid"
    )
    is_vegetarian: bool = Field(
        default=False,
        description="Whether they avoid meat"
    )
    is_vegan: bool = Field(
        default=False,
        description="Whether they avoid all animal products"
    )
    food_allergies: list[str] = Field(
        default_factory=list,
        description="Foods they're allergic to"
    )
    is_greedy_eater: bool = Field(
        default=False,
        description="Whether they tend to overeat"
    )
    is_picky_eater: bool = Field(
        default=False,
        description="Whether they're particular about food"
    )

    # Drink preferences
    favorite_drinks: list[str] = Field(
        default_factory=list,
        description="Drinks they particularly enjoy"
    )
    disliked_drinks: list[str] = Field(
        default_factory=list,
        description="Drinks they dislike or avoid"
    )
    is_alcoholic: bool = Field(
        default=False,
        description="Whether they have a drinking problem"
    )
    is_teetotaler: bool = Field(
        default=False,
        description="Whether they abstain from alcohol"
    )

    # Activities and general preferences
    favorite_activities: list[str] = Field(
        default_factory=list,
        description="Activities they enjoy"
    )
    dislikes: list[str] = Field(
        default_factory=list,
        description="Personality traits or behaviors they dislike"
    )
    fears: list[str] = Field(
        default_factory=list,
        description="Things they fear"
    )

    # Intimacy preferences
    drive_level: str = Field(
        default="moderate",
        description="Intimacy drive level: 'low', 'moderate', 'high'"
    )
    drive_threshold: int = Field(
        default=50,
        ge=0,
        le=100,
        description="Need threshold at which they seek intimacy"
    )
    has_regular_partner: bool = Field(
        default=False,
        description="Whether they have a committed partner"
    )
    is_actively_seeking: bool = Field(
        default=False,
        description="Whether they're actively looking for romance"
    )

    # Sleep/stamina preferences
    has_high_stamina: bool = Field(
        default=False,
        description="Whether they have above-average stamina"
    )
    has_low_stamina: bool = Field(
        default=False,
        description="Whether they tire easily"
    )
    is_insomniac: bool = Field(
        default=False,
        description="Whether they have trouble sleeping"
    )
    is_heavy_sleeper: bool = Field(
        default=False,
        description="Whether they sleep deeply and are hard to wake"
    )

    # Extensibility
    extra_preferences: dict = Field(
        default_factory=dict,
        description="Additional custom preferences"
    )


class NPCNeeds(BaseModel):
    """Current need levels (0-100 scale, higher = more urgent)."""

    hunger: int = Field(default=30, ge=0, le=100)
    thirst: int = Field(default=30, ge=0, le=100)
    fatigue: int = Field(default=20, ge=0, le=100)
    social: int = Field(default=40, ge=0, le=100)
    comfort: int = Field(default=50, ge=0, le=100)
    hygiene: int = Field(default=30, ge=0, le=100)
    morale: int = Field(default=50, ge=0, le=100)
    intimacy: int = Field(default=30, ge=0, le=100)


class NPCCurrentState(BaseModel):
    """Current situational state of the NPC."""

    mood: str = Field(description="Current emotional state, e.g. 'bored but hopeful'")
    health: str = Field(default="healthy", description="Health status")
    conditions: list[str] = Field(
        default_factory=list,
        description="Current conditions, e.g. ['slightly dehydrated', 'tired']"
    )
    current_activity: str = Field(description="What they're currently doing")
    current_location: str = Field(description="Location key where they are")


class AttractionScore(BaseModel):
    """Attraction/compatibility score breakdown."""

    physical: float = Field(ge=0, le=1, description="Physical attraction (0-1)")
    personality: float = Field(ge=0, le=1, description="Personality compatibility (0-1)")
    overall: float = Field(ge=0, le=1, description="Combined attraction score (0-1)")


class EnvironmentalReaction(BaseModel):
    """NPC's reaction to something in the environment."""

    notices: str = Field(description="What the NPC notices")
    reaction_type: Literal[
        "need_triggered",
        "attraction",
        "fear",
        "curiosity",
        "recognition",
        "suspicion",
        "comfort",
        "discomfort"
    ] = Field(description="Type of reaction")

    # Need-based reaction details
    need_triggered: str | None = Field(
        default=None,
        description="Which need this triggers, e.g. 'thirst', 'hunger'"
    )
    intensity: Literal["mild", "moderate", "strong", "overwhelming"] | None = Field(
        default=None,
        description="How strongly the need is triggered"
    )

    # Attraction-based reaction details
    attraction_score: AttractionScore | None = Field(
        default=None,
        description="Attraction score breakdown if reaction_type is 'attraction'"
    )

    # All reactions
    internal_thought: str = Field(
        description="What they're thinking (GM-only)"
    )
    likely_behavior: str = Field(
        description="How they're likely to act on this"
    )


class ImmediateGoal(BaseModel):
    """An immediate short-term goal the NPC has."""

    goal: str = Field(description="What they want to accomplish")
    priority: Literal["urgent", "primary", "secondary", "opportunity"] = Field(
        description="How important this goal is right now"
    )


# =============================================================================
# Main NPC State Schemas
# =============================================================================


class NPCFullState(BaseModel):
    """Complete NPC state returned by create_npc tool.

    This represents the full, rich state of an NPC including:
    - Identity (key, name, appearance)
    - Background and history
    - Personality (traits, values, flaws)
    - Preferences (attractions, favorites, aversions)
    - Current needs
    - Current situational state
    - Environmental reactions (what they notice and how they react)
    - Immediate goals
    - Behavioral prediction

    Both precise data (for database) and narrative descriptions (for GM) are included.
    """

    # Identity
    entity_key: str = Field(
        description="Unique identifier, e.g. 'customer_elara', 'guard_marcus'"
    )
    display_name: str = Field(
        description="Full display name, e.g. 'Elara Thornwood'"
    )

    # Components
    appearance: NPCAppearance
    background: NPCBackground
    personality: NPCPersonality
    preferences: NPCPreferences
    current_needs: NPCNeeds
    current_state: NPCCurrentState

    # Environmental awareness
    environmental_reactions: list[EnvironmentalReaction] = Field(
        default_factory=list,
        description="Reactions to things in the current scene"
    )

    # Goals
    immediate_goals: list[ImmediateGoal] = Field(
        default_factory=list,
        description="Short-term goals based on current situation"
    )

    # Behavioral prediction for GM
    behavioral_prediction: str = Field(
        description="GM guidance on how NPC is likely to behave"
    )

    class Config:
        """Pydantic configuration."""

        json_schema_extra = {
            "example": {
                "entity_key": "customer_elara",
                "display_name": "Elara Thornwood",
                "appearance": {
                    "age": 23,
                    "gender": "female",
                    "height_cm": 168,
                    "species": "human",
                    "age_description": "early twenties",
                    "height_description": "average height",
                    "build": "athletic",
                    "hair": "auburn, worn in a practical braid",
                    "eyes": "bright green",
                    "skin": "fair with freckles across nose and cheeks",
                    "notable_features": ["calloused hands from herbalist work"],
                    "clothing": "simple green dress, worn leather boots"
                },
                "background": {
                    "occupation": "herbalist apprentice",
                    "occupation_years": 8,
                    "birthplace": "Millbrook",
                    "family": "parents deceased, raised by aunt",
                    "background_summary": "Apprentice herbalist who dreams of adventure"
                },
                "personality": {
                    "traits": ["shy", "curious", "romantic", "hardworking"],
                    "values": ["honesty", "nature", "loyalty"],
                    "flaws": ["indecisive", "overthinks"],
                    "quirks": ["touches hair when nervous"]
                },
                "preferences": {
                    "attracted_to_genders": ["male"],
                    "attracted_age_offset": 2,
                    "attracted_to_physical": ["lean build", "dark hair"],
                    "attracted_to_personality": ["confidence", "kindness"],
                    "favorite_foods": ["honey cakes"],
                    "disliked_foods": ["liver"],
                    "is_vegetarian": False,
                    "is_vegan": False,
                    "food_allergies": [],
                    "is_greedy_eater": False,
                    "is_picky_eater": False,
                    "favorite_drinks": ["chamomile tea"],
                    "disliked_drinks": ["strong ale"],
                    "is_alcoholic": False,
                    "is_teetotaler": False,
                    "favorite_activities": ["reading", "foraging"],
                    "dislikes": ["arrogance", "cruelty"],
                    "fears": ["being alone forever"],
                    "drive_level": "moderate",
                    "drive_threshold": 50,
                    "has_regular_partner": False,
                    "is_actively_seeking": True,
                    "has_high_stamina": False,
                    "has_low_stamina": False,
                    "is_insomniac": False,
                    "is_heavy_sleeper": False,
                    "extra_preferences": {}
                },
                "current_needs": {
                    "hunger": 45,
                    "thirst": 78,
                    "fatigue": 30,
                    "social": 65,
                    "comfort": 50,
                    "hygiene": 70,
                    "morale": 55,
                    "intimacy": 40
                },
                "current_state": {
                    "mood": "bored but hopeful",
                    "health": "healthy",
                    "conditions": ["slightly dehydrated"],
                    "current_activity": "shopping for dried goods",
                    "current_location": "general_store"
                },
                "environmental_reactions": [
                    {
                        "notices": "player's water bottle",
                        "reaction_type": "need_triggered",
                        "need_triggered": "thirst",
                        "intensity": "strong",
                        "internal_thought": "That water looks so refreshing...",
                        "likely_behavior": "keeps glancing at bottle"
                    }
                ],
                "immediate_goals": [
                    {"goal": "buy dried herbs", "priority": "primary"},
                    {"goal": "get something to drink", "priority": "urgent"}
                ],
                "behavioral_prediction": "Thirst + attraction may override natural shyness"
            }
        }


class NPCReactions(BaseModel):
    """Updated NPC reactions returned by query_npc tool.

    Used when checking an existing NPC's current state and reactions
    to a changed scene.
    """

    entity_key: str = Field(description="Entity key of the NPC")
    current_needs: NPCNeeds = Field(description="Updated need levels")
    current_mood: str = Field(description="Current emotional state")
    environmental_reactions: list[EnvironmentalReaction] = Field(
        default_factory=list,
        description="Reactions to current scene"
    )
    behavioral_prediction: str = Field(
        description="How they're likely to behave given current state"
    )


# =============================================================================
# Scene Context (Input to Tools)
# =============================================================================


class VisibleItem(BaseModel):
    """An item visible in the scene."""

    item_key: str
    display_name: str
    brief_description: str
    holder_key: str | None = Field(
        default=None,
        description="Entity holding this item (if any)"
    )


class PlayerSummary(BaseModel):
    """Summary of player state visible to NPCs."""

    appearance_summary: str = Field(
        description="Brief description of player's appearance"
    )
    visible_items: list[str] = Field(
        default_factory=list,
        description="Items the player has that NPCs can see"
    )
    visible_conditions: list[str] = Field(
        default_factory=list,
        description="Visible conditions, e.g. 'wounded', 'well-dressed'"
    )
    current_activity: str | None = Field(
        default=None,
        description="What the player appears to be doing"
    )


class SceneContext(BaseModel):
    """Context about the current scene, passed to NPC creation/query tools.

    This provides the situational awareness NPCs need to react authentically.
    """

    location_key: str = Field(description="Current location key")
    location_description: str = Field(description="Brief description of the location")
    entities_present: list[str] = Field(
        default_factory=list,
        description="Entity keys of everyone present (including player)"
    )
    visible_items: list[VisibleItem] = Field(
        default_factory=list,
        description="Items visible in the scene"
    )
    environment: list[str] = Field(
        default_factory=list,
        description="Environmental factors: 'warm', 'smells of bread', 'crowded'"
    )
    player_visible_state: PlayerSummary | None = Field(
        default=None,
        description="Player state visible to NPCs"
    )
    time_of_day: str | None = Field(
        default=None,
        description="Current time, e.g. 'morning', 'evening', '14:30'"
    )
    weather: str | None = Field(
        default=None,
        description="Current weather if relevant"
    )


# =============================================================================
# NPC Creation Constraints
# =============================================================================


class NPCConstraints(BaseModel):
    """Optional constraints for NPC creation.

    When the GM needs specific traits for story purposes, these constraints
    override the random generation. If not specified, traits are emergent.
    """

    # Identity constraints
    name: str | None = Field(default=None, description="Specific name if needed")
    gender: str | None = Field(default=None, description="Specific gender")
    age_range: Literal[
        "child", "teen", "young_adult", "middle_aged", "elderly"
    ] | None = Field(default=None, description="Age range")
    age_exact: int | None = Field(default=None, ge=0, le=200, description="Exact age")
    species: str | None = Field(default=None, description="Species/race")

    # Background constraints
    occupation: str | None = Field(default=None, description="Specific occupation")
    wealth_level: Literal[
        "destitute", "poor", "modest", "comfortable", "wealthy", "rich"
    ] | None = Field(default=None, description="Economic status")

    # Personality constraints
    personality: list[str] | None = Field(
        default=None,
        description="Required personality traits"
    )

    # Disposition constraints
    hostile_to_player: bool | None = Field(
        default=None,
        description="Must be antagonistic"
    )
    friendly_to_player: bool | None = Field(
        default=None,
        description="Must be welcoming"
    )
    attracted_to_player: bool | None = Field(
        default=None,
        description="Force positive attraction check"
    )

    # Backstory NPC constraints (for family/friends from character creation)
    relationship_role: str | None = Field(
        default=None,
        description="Specific relationship role (e.g., 'younger brother', 'mother', 'mentor')"
    )
    relationship_context: str | None = Field(
        default=None,
        description="Emotional context of relationship (e.g., 'idolizes player', 'protective of player')"
    )
    brief_appearance: str | None = Field(
        default=None,
        description="Physical appearance description for backstory NPCs"
    )
