"""add mentioned_items to turns

Revision ID: 0ad9be14ad12
Revises: 90c258815db1
Create Date: 2025-12-19 08:28:55.105495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ad9be14ad12'
down_revision: Union[str, None] = '90c258815db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entities', 'temporary_state',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Transient entity state (posture, position, temporary conditions)',
               existing_nullable=True)
    op.add_column('turns', sa.Column('mentioned_items', sa.JSON(), nullable=True, comment='[{name, context, location}] - decorative items for deferred spawn'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'mentioned_items')
    op.alter_column('entities', 'temporary_state',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Transient entity state (posture, position, temporary conditions)',
               existing_nullable=True)
    # ### end Alembic commands ###
