"""add_relationship_arcs_table

Revision ID: 111af31a57d1
Revises: 232c117be2f2
Create Date: 2025-12-11 16:27:53.194109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '111af31a57d1'
down_revision: Union[str, None] = '232c117be2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship_arcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('arc_key', sa.String(length=100), nullable=False),
    sa.Column('arc_type', sa.String(length=30), nullable=False),
    sa.Column('entity1_key', sa.String(length=100), nullable=False),
    sa.Column('entity2_key', sa.String(length=100), nullable=False),
    sa.Column('current_phase', sa.String(length=20), nullable=False),
    sa.Column('phase_progress', sa.Integer(), nullable=False),
    sa.Column('milestones_hit', sa.JSON(), nullable=False),
    sa.Column('suggested_next_beat', sa.String(length=500), nullable=True),
    sa.Column('arc_tension', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_turn', sa.Integer(), nullable=False),
    sa.Column('completed_turn', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'arc_key', name='uq_relationship_arc_session_key')
    )
    op.create_index(op.f('ix_relationship_arcs_entity1_key'), 'relationship_arcs', ['entity1_key'], unique=False)
    op.create_index(op.f('ix_relationship_arcs_entity2_key'), 'relationship_arcs', ['entity2_key'], unique=False)
    op.create_index(op.f('ix_relationship_arcs_session_id'), 'relationship_arcs', ['session_id'], unique=False)
    op.alter_column('rumors', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rumors', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_relationship_arcs_session_id'), table_name='relationship_arcs')
    op.drop_index(op.f('ix_relationship_arcs_entity2_key'), table_name='relationship_arcs')
    op.drop_index(op.f('ix_relationship_arcs_entity1_key'), table_name='relationship_arcs')
    op.drop_table('relationship_arcs')
    # ### end Alembic commands ###
