"""add_item_weight_field

Revision ID: 12d9e2934e02
Revises: 4fbbe5395f6d
Create Date: 2025-12-11 20:45:49.871185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d9e2934e02'
down_revision: Union[str, None] = '4fbbe5395f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('weight', sa.Float(), nullable=True, comment='Weight in pounds (for encumbrance calculation)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'weight')
    # ### end Alembic commands ###
