"""add_storage_observations_table

Revision ID: 1d4fed343685
Revises: 858b279a2ac6
Create Date: 2025-12-25 10:07:35.753610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4fed343685'
down_revision: Union[str, None] = '858b279a2ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('observer_id', sa.Integer(), nullable=False, comment='Entity that observed this storage (usually player)'),
    sa.Column('storage_location_id', sa.Integer(), nullable=False, comment='The storage container that was observed'),
    sa.Column('observed_at_turn', sa.Integer(), nullable=False, comment='Turn number when first observed'),
    sa.Column('observed_at_game_day', sa.Integer(), nullable=False, comment='In-game day when first observed'),
    sa.Column('observed_at_game_time', sa.String(length=5), nullable=True, comment='In-game time when first observed (HH:MM)'),
    sa.Column('contents_snapshot', sa.JSON(), nullable=True, comment='List of item_keys present when first observed'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['observer_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'observer_id', 'storage_location_id', name='uq_storage_observation_session_observer_storage')
    )
    op.create_index(op.f('ix_storage_observations_id'), 'storage_observations', ['id'], unique=False)
    op.create_index(op.f('ix_storage_observations_observer_id'), 'storage_observations', ['observer_id'], unique=False)
    op.create_index(op.f('ix_storage_observations_session_id'), 'storage_observations', ['session_id'], unique=False)
    op.create_index(op.f('ix_storage_observations_storage_location_id'), 'storage_observations', ['storage_location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_observations_storage_location_id'), table_name='storage_observations')
    op.drop_index(op.f('ix_storage_observations_session_id'), table_name='storage_observations')
    op.drop_index(op.f('ix_storage_observations_observer_id'), table_name='storage_observations')
    op.drop_index(op.f('ix_storage_observations_id'), table_name='storage_observations')
    op.drop_table('storage_observations')
    # ### end Alembic commands ###
