"""add_rumor_system_tables

Revision ID: 232c117be2f2
Revises: a3c9cc28fc46
Create Date: 2025-12-11 16:22:50.086588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '232c117be2f2'
down_revision: Union[str, None] = 'a3c9cc28fc46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rumors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('rumor_key', sa.String(length=100), nullable=False),
    sa.Column('subject_entity_key', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('truth_value', sa.Float(), nullable=False),
    sa.Column('original_event_id', sa.Integer(), nullable=True),
    sa.Column('origin_location_key', sa.String(length=100), nullable=False),
    sa.Column('origin_turn', sa.Integer(), nullable=False),
    sa.Column('spread_rate', sa.Float(), nullable=False),
    sa.Column('decay_rate', sa.Float(), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'rumor_key', name='uq_rumor_session_key')
    )
    op.create_index(op.f('ix_rumors_session_id'), 'rumors', ['session_id'], unique=False)
    op.create_index(op.f('ix_rumors_subject_entity_key'), 'rumors', ['subject_entity_key'], unique=False)
    op.create_table('rumor_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('rumor_id', sa.Integer(), nullable=False),
    sa.Column('entity_key', sa.String(length=100), nullable=False),
    sa.Column('learned_turn', sa.Integer(), nullable=False),
    sa.Column('believed', sa.Boolean(), nullable=False),
    sa.Column('will_spread', sa.Boolean(), nullable=False),
    sa.Column('local_distortion', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['rumor_id'], ['rumors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'rumor_id', 'entity_key', name='uq_rumor_knowledge_entity')
    )
    op.create_index(op.f('ix_rumor_knowledge_entity_key'), 'rumor_knowledge', ['entity_key'], unique=False)
    op.create_index(op.f('ix_rumor_knowledge_rumor_id'), 'rumor_knowledge', ['rumor_id'], unique=False)
    op.create_index(op.f('ix_rumor_knowledge_session_id'), 'rumor_knowledge', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rumor_knowledge_session_id'), table_name='rumor_knowledge')
    op.drop_index(op.f('ix_rumor_knowledge_rumor_id'), table_name='rumor_knowledge')
    op.drop_index(op.f('ix_rumor_knowledge_entity_key'), table_name='rumor_knowledge')
    op.drop_table('rumor_knowledge')
    op.drop_index(op.f('ix_rumors_subject_entity_key'), table_name='rumors')
    op.drop_index(op.f('ix_rumors_session_id'), table_name='rumors')
    op.drop_table('rumors')
    # ### end Alembic commands ###
