"""add_relationship_milestones

Revision ID: 2564a021f6ff
Revises: 79d56dc7020f
Create Date: 2025-12-11 15:07:39.629200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2564a021f6ff'
down_revision: Union[str, None] = '79d56dc7020f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('milestone_type', sa.String(length=50), nullable=False, comment='Type: earned_trust, became_friends, made_enemy, etc.'),
    sa.Column('dimension', sa.String(length=30), nullable=False, comment='Which dimension triggered this milestone'),
    sa.Column('threshold_value', sa.Integer(), nullable=False, comment='Value that was crossed to trigger milestone'),
    sa.Column('direction', sa.String(length=10), nullable=False, comment='up or down - direction of threshold crossing'),
    sa.Column('message', sa.String(length=200), nullable=False, comment='Player-facing notification message'),
    sa.Column('notified', sa.Boolean(), nullable=False, comment='Whether player has been notified'),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_milestones_id'), 'relationship_milestones', ['id'], unique=False)
    op.create_index(op.f('ix_relationship_milestones_relationship_id'), 'relationship_milestones', ['relationship_id'], unique=False)
    op.create_index(op.f('ix_relationship_milestones_turn_number'), 'relationship_milestones', ['turn_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationship_milestones_turn_number'), table_name='relationship_milestones')
    op.drop_index(op.f('ix_relationship_milestones_relationship_id'), table_name='relationship_milestones')
    op.drop_index(op.f('ix_relationship_milestones_id'), table_name='relationship_milestones')
    op.drop_table('relationship_milestones')
    # ### end Alembic commands ###
