"""add_theft_tracking_and_storage_enhancements

Revision ID: 25d0fb8756ad
Revises: 7deb1bdd87cc
Create Date: 2025-12-14 07:49:20.509602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d0fb8756ad'
down_revision: Union[str, None] = '7deb1bdd87cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Item theft tracking fields (with server_default for existing data)
    op.add_column('items', sa.Column('is_stolen', sa.Boolean(), nullable=False, server_default='false', comment='Item is currently stolen (clears on legitimate transfer)'))
    op.add_column('items', sa.Column('was_ever_stolen', sa.Boolean(), nullable=False, server_default='false', comment='Historical flag - item was stolen at some point (never clears)'))
    op.add_column('items', sa.Column('stolen_from_id', sa.Integer(), nullable=True, comment='Entity this was stolen from (for returning)'))
    op.add_column('items', sa.Column('stolen_from_location_id', sa.Integer(), nullable=True, comment='Location/establishment this was stolen from'))
    op.add_column('items', sa.Column('original_owner_id', sa.Integer(), nullable=True, comment='First known owner (provenance tracking)'))
    op.add_column('items', sa.Column('owner_location_id', sa.Integer(), nullable=True, comment="Location that owns this item (e.g., inn's bowls) - mutually exclusive with owner_id"))
    op.create_foreign_key(None, 'items', 'locations', ['owner_location_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'items', 'entities', ['stolen_from_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'items', 'entities', ['original_owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'items', 'locations', ['stolen_from_location_id'], ['id'], ondelete='SET NULL')

    # StorageLocation new fields (with server_default for existing data)
    op.add_column('storage_locations', sa.Column('container_item_id', sa.Integer(), nullable=True, comment='The Item this storage represents (backpack, pouch, chest)'))
    op.add_column('storage_locations', sa.Column('is_fixed', sa.Boolean(), nullable=False, server_default='false', comment='Cannot be moved (built-in closet, fixed chest)'))
    op.add_column('storage_locations', sa.Column('weight_to_move', sa.Float(), nullable=True, comment='Weight for strength check to move (heavy but not fixed)'))
    op.add_column('storage_locations', sa.Column('weight_capacity', sa.Float(), nullable=True, comment='Max weight this can hold (in addition to item count capacity)'))
    op.add_column('storage_locations', sa.Column('owner_location_id', sa.Integer(), nullable=True, comment='Location that owns this storage - mutually exclusive with owner_entity_id'))
    op.create_unique_constraint(None, 'storage_locations', ['container_item_id'])
    op.create_foreign_key(None, 'storage_locations', 'items', ['container_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'storage_locations', 'locations', ['owner_location_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'storage_locations', type_='foreignkey')
    op.drop_constraint(None, 'storage_locations', type_='foreignkey')
    op.drop_constraint(None, 'storage_locations', type_='unique')
    op.drop_column('storage_locations', 'owner_location_id')
    op.drop_column('storage_locations', 'weight_capacity')
    op.drop_column('storage_locations', 'weight_to_move')
    op.drop_column('storage_locations', 'is_fixed')
    op.drop_column('storage_locations', 'container_item_id')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'owner_location_id')
    op.drop_column('items', 'original_owner_id')
    op.drop_column('items', 'stolen_from_location_id')
    op.drop_column('items', 'stolen_from_id')
    op.drop_column('items', 'was_ever_stolen')
    op.drop_column('items', 'is_stolen')
    # ### end Alembic commands ###
