"""add_birthplace_to_entities

Revision ID: 369661c753f3
Revises: 012
Create Date: 2025-12-11 11:29:57.176064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '369661c753f3'
down_revision: Union[str, None] = '012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode_key', sa.String(length=50), nullable=False, comment="Unique key (e.g., 'walking', 'mounted', 'swimming')"),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('transport_type', sa.Enum('walking', 'running', 'mounted', 'swimming', 'climbing', 'flying', 'boat', 'ship', 'vehicle', name='transporttype'), nullable=False),
    sa.Column('terrain_costs', sa.JSON(), nullable=False, comment='Map of terrain_type to cost multiplier (null = impassable)'),
    sa.Column('requires_skill', sa.String(length=50), nullable=True, comment='Skill required to use this mode'),
    sa.Column('requires_item', sa.String(length=100), nullable=True, comment="Item required (e.g., 'horse', 'boat')"),
    sa.Column('fatigue_rate', sa.Float(), nullable=False, comment='Energy cost multiplier per unit time'),
    sa.Column('encounter_modifier', sa.Float(), nullable=False, comment='Encounter chance multiplier (0.5 = fewer, 2.0 = more)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transport_modes_id'), 'transport_modes', ['id'], unique=False)
    op.create_index(op.f('ix_transport_modes_mode_key'), 'transport_modes', ['mode_key'], unique=True)
    op.create_table('digital_map_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('service_key', sa.String(length=50), nullable=False, comment="Unique key (e.g., 'google_maps', 'starship_nav')"),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('requires_device', sa.Boolean(), nullable=False, comment='Needs phone/laptop/terminal?'),
    sa.Column('requires_connection', sa.Boolean(), nullable=False, comment='Needs wifi/mobile data/network?'),
    sa.Column('coverage_map_type', sa.Enum('world', 'regional', 'city', 'dungeon', 'building', name='maptype'), nullable=False, comment='What level of detail this service provides'),
    sa.Column('is_available', sa.Boolean(), nullable=False, comment='Currently accessible in the game world?'),
    sa.Column('unavailable_reason', sa.Text(), nullable=True, comment='Why service is unavailable (no signal, server down, etc.)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'service_key', name='uq_digital_map_access_session_service')
    )
    op.create_index(op.f('ix_digital_map_access_id'), 'digital_map_access', ['id'], unique=False)
    op.create_index(op.f('ix_digital_map_access_service_key'), 'digital_map_access', ['service_key'], unique=False)
    op.create_index(op.f('ix_digital_map_access_session_id'), 'digital_map_access', ['session_id'], unique=False)
    op.create_table('terrain_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('zone_key', sa.String(length=100), nullable=False, comment="Unique key (e.g., 'darkwood_forest_north')"),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('terrain_type', sa.Enum('plains', 'forest', 'road', 'trail', 'mountain', 'swamp', 'desert', 'lake', 'river', 'ocean', 'cliff', 'cave', 'urban', 'ruins', name='terraintype'), nullable=False),
    sa.Column('parent_zone_id', sa.Integer(), nullable=True),
    sa.Column('base_travel_cost', sa.Integer(), nullable=False, comment='Base walking time in minutes per unit distance'),
    sa.Column('mounted_travel_cost', sa.Integer(), nullable=True, comment='Travel time on mount (null = impassable by mount)'),
    sa.Column('requires_skill', sa.String(length=50), nullable=True, comment="Skill required to enter (e.g., 'swimming', 'climbing')"),
    sa.Column('skill_difficulty', sa.Integer(), nullable=True, comment='DC for skill check if required'),
    sa.Column('failure_consequence', sa.String(length=100), nullable=True, comment="What happens on failed check (e.g., 'drowning', 'fall_damage')"),
    sa.Column('visibility_range', sa.Enum('far', 'medium', 'short', 'none', name='visibilityrange'), nullable=False, comment='How far player can see in this zone'),
    sa.Column('encounter_frequency', sa.Enum('none', 'low', 'medium', 'high', 'very_high', name='encounterfrequency'), nullable=False),
    sa.Column('encounter_table_key', sa.String(length=100), nullable=True, comment='Key to encounter table for this zone'),
    sa.Column('description', sa.Text(), nullable=False, comment='Full description of the zone'),
    sa.Column('atmosphere', sa.Text(), nullable=True, comment='Mood, sounds, smells'),
    sa.Column('is_accessible', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True, comment='Why zone is blocked (fire, flood, etc.)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_zone_id'], ['terrain_zones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'zone_key', name='uq_terrain_zone_session_key')
    )
    op.create_index(op.f('ix_terrain_zones_id'), 'terrain_zones', ['id'], unique=False)
    op.create_index(op.f('ix_terrain_zones_session_id'), 'terrain_zones', ['session_id'], unique=False)
    op.create_index(op.f('ix_terrain_zones_terrain_type'), 'terrain_zones', ['terrain_type'], unique=False)
    op.create_index(op.f('ix_terrain_zones_zone_key'), 'terrain_zones', ['zone_key'], unique=False)
    op.create_table('character_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False, comment="What is remembered: 'mother's hat', 'red chicken', 'house fire'"),
    sa.Column('subject_type', sa.Enum('PERSON', 'ITEM', 'PLACE', 'EVENT', 'CREATURE', 'CONCEPT', name='memorytype'), nullable=False, comment='Type of memory subject (person, item, place, event, creature, concept)'),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment="Keywords for matching: ['hat', 'wide-brimmed', 'straw']"),
    sa.Column('valence', sa.Enum('POSITIVE', 'NEGATIVE', 'MIXED', 'NEUTRAL', name='emotionalvalence'), nullable=False, comment='Emotional direction: positive, negative, mixed, neutral'),
    sa.Column('emotion', sa.String(length=50), nullable=False, comment="Primary emotion: 'grief', 'joy', 'fear', 'curiosity', 'nostalgia'"),
    sa.Column('context', sa.Text(), nullable=False, comment="Why this is meaningful: 'Mother wore this hat every summer before she died'"),
    sa.Column('source', sa.String(length=50), nullable=False, comment="Where memory came from: 'backstory', 'gameplay', 'relationship'"),
    sa.Column('intensity', sa.Integer(), nullable=False, comment='How strongly this affects character (1-10)'),
    sa.Column('created_turn', sa.Integer(), nullable=True, comment='Turn number when memory was created (null for backstory)'),
    sa.Column('last_triggered_turn', sa.Integer(), nullable=True, comment='Turn number when memory was last activated'),
    sa.Column('trigger_count', sa.Integer(), nullable=False, comment='How many times this memory has been triggered'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_memories_entity_id'), 'character_memories', ['entity_id'], unique=False)
    op.create_index(op.f('ix_character_memories_id'), 'character_memories', ['id'], unique=False)
    op.create_index(op.f('ix_character_memories_session_id'), 'character_memories', ['session_id'], unique=False)
    op.create_table('location_zone_placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('placement_type', sa.Enum('within', 'edge', 'landmark', name='placementtype'), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False, comment='visible_from_zone, hidden, requires_search'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['terrain_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'location_id', name='uq_location_zone_placement_location')
    )
    op.create_index(op.f('ix_location_zone_placements_id'), 'location_zone_placements', ['id'], unique=False)
    op.create_index(op.f('ix_location_zone_placements_location_id'), 'location_zone_placements', ['location_id'], unique=False)
    op.create_index(op.f('ix_location_zone_placements_session_id'), 'location_zone_placements', ['session_id'], unique=False)
    op.create_index(op.f('ix_location_zone_placements_zone_id'), 'location_zone_placements', ['zone_id'], unique=False)
    op.create_table('zone_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('from_zone_id', sa.Integer(), nullable=False),
    sa.Column('to_zone_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=30), nullable=True, comment='Direction: north, south, east, west, up, down, inside, etc.'),
    sa.Column('connection_type', sa.Enum('open', 'path', 'bridge', 'climb', 'swim', 'door', 'gate', 'hidden', name='connectiontype'), nullable=False),
    sa.Column('crossing_minutes', sa.Integer(), nullable=False, comment='Time to cross this connection in minutes'),
    sa.Column('requires_skill', sa.String(length=50), nullable=True, comment='Skill required to cross (additional to destination zone)'),
    sa.Column('skill_difficulty', sa.Integer(), nullable=True, comment='DC for crossing skill check'),
    sa.Column('is_bidirectional', sa.Boolean(), nullable=False, comment='Can travel both ways?'),
    sa.Column('is_passable', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True, comment='Why connection is blocked (bridge destroyed, locked, etc.)'),
    sa.Column('is_visible', sa.Boolean(), nullable=False, comment='False for secret passages'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of the path/passage'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_zone_id'], ['terrain_zones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_zone_id'], ['terrain_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_zone_connection_from_passable', 'zone_connections', ['from_zone_id', 'is_passable'], unique=False)
    op.create_index(op.f('ix_zone_connections_from_zone_id'), 'zone_connections', ['from_zone_id'], unique=False)
    op.create_index(op.f('ix_zone_connections_id'), 'zone_connections', ['id'], unique=False)
    op.create_index(op.f('ix_zone_connections_session_id'), 'zone_connections', ['session_id'], unique=False)
    op.create_index(op.f('ix_zone_connections_to_zone_id'), 'zone_connections', ['to_zone_id'], unique=False)
    op.create_table('location_discoveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('discovered_turn', sa.Integer(), nullable=False, comment='Turn when location was discovered'),
    sa.Column('discovery_method', sa.Enum('visited', 'told_by_npc', 'map_viewed', 'digital_lookup', 'visible_from', 'starting_knowledge', name='discoverymethod'), nullable=False),
    sa.Column('source_map_id', sa.Integer(), nullable=True, comment='If discovered via map item'),
    sa.Column('source_entity_id', sa.Integer(), nullable=True, comment='If told by NPC'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_map_id'], ['items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'location_id', name='uq_location_discovery_session_location')
    )
    op.create_index(op.f('ix_location_discoveries_id'), 'location_discoveries', ['id'], unique=False)
    op.create_index(op.f('ix_location_discoveries_location_id'), 'location_discoveries', ['location_id'], unique=False)
    op.create_index(op.f('ix_location_discoveries_session_id'), 'location_discoveries', ['session_id'], unique=False)
    op.create_table('map_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('map_type', sa.Enum('world', 'regional', 'city', 'dungeon', 'building', name='maptype'), nullable=False),
    sa.Column('coverage_zone_id', sa.Integer(), nullable=True, comment='Root zone this map covers (and all children)'),
    sa.Column('is_complete', sa.Boolean(), nullable=False, comment='Full map or partial/damaged?'),
    sa.Column('revealed_zone_ids', sa.JSON(), nullable=True, comment='Specific zone IDs this map reveals'),
    sa.Column('revealed_location_ids', sa.JSON(), nullable=True, comment='Specific location IDs this map reveals'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coverage_zone_id'], ['terrain_zones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_items_id'), 'map_items', ['id'], unique=False)
    op.create_index(op.f('ix_map_items_item_id'), 'map_items', ['item_id'], unique=True)
    op.create_index(op.f('ix_map_items_session_id'), 'map_items', ['session_id'], unique=False)
    op.create_table('zone_discoveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('discovered_turn', sa.Integer(), nullable=False, comment='Turn when zone was discovered'),
    sa.Column('discovery_method', sa.Enum('visited', 'told_by_npc', 'map_viewed', 'digital_lookup', 'visible_from', 'starting_knowledge', name='discoverymethod'), nullable=False),
    sa.Column('source_map_id', sa.Integer(), nullable=True, comment='If discovered via map item'),
    sa.Column('source_entity_id', sa.Integer(), nullable=True, comment='If told by NPC'),
    sa.Column('source_zone_id', sa.Integer(), nullable=True, comment='If visible from another zone'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_map_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_zone_id'], ['terrain_zones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['terrain_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'zone_id', name='uq_zone_discovery_session_zone')
    )
    op.create_index(op.f('ix_zone_discoveries_id'), 'zone_discoveries', ['id'], unique=False)
    op.create_index(op.f('ix_zone_discoveries_session_id'), 'zone_discoveries', ['session_id'], unique=False)
    op.create_index(op.f('ix_zone_discoveries_zone_id'), 'zone_discoveries', ['zone_id'], unique=False)
    op.drop_index('ix_intimacy_profiles_entity_id', table_name='intimacy_profiles')
    op.drop_index('ix_intimacy_profiles_id', table_name='intimacy_profiles')
    op.drop_index('ix_intimacy_profiles_session_id', table_name='intimacy_profiles')
    op.drop_table('intimacy_profiles')
    op.add_column('character_needs', sa.Column('thirst', sa.Integer(), nullable=False, server_default='70', comment='0=dehydrated, 50=satisfied, 100=well-hydrated. Optimal: 40-80'))
    op.add_column('character_needs', sa.Column('hunger_craving', sa.Integer(), nullable=False, server_default='0', comment='Temporary hunger urgency boost from stimuli (0-100)'))
    op.add_column('character_needs', sa.Column('thirst_craving', sa.Integer(), nullable=False, server_default='0', comment='Temporary thirst urgency boost from stimuli (0-100)'))
    op.add_column('character_needs', sa.Column('energy_craving', sa.Integer(), nullable=False, server_default='0', comment='Temporary fatigue urgency boost from stimuli (0-100)'))
    op.add_column('character_needs', sa.Column('social_craving', sa.Integer(), nullable=False, server_default='0', comment='Temporary social urgency boost from stimuli (0-100)'))
    op.add_column('character_needs', sa.Column('intimacy_craving', sa.Integer(), nullable=False, server_default='0', comment='Temporary intimacy urgency boost from stimuli (0-100)'))
    op.add_column('character_needs', sa.Column('last_drink_turn', sa.Integer(), nullable=True))
    op.alter_column('character_needs', 'energy',
               existing_type=sa.INTEGER(),
               comment='0=exhausted, 50=tired, 100=energized. Optimal: 60-100',
               existing_nullable=False,
               existing_server_default=sa.text('80'))
    op.alter_column('character_needs', 'wellness',
               existing_type=sa.INTEGER(),
               comment='0=agony (from injuries), 100=pain-free',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('character_needs', 'intimacy',
               existing_type=sa.INTEGER(),
               comment='0=desperate, 100=content. Intimacy fulfillment level.',
               existing_comment='0=satisfied, 100=desperate. Intimacy need level.',
               existing_nullable=False)
    op.add_column('entities', sa.Column('birthplace', sa.String(length=100), nullable=True, comment="Region/place of birth (e.g., 'Northern Europe', 'Mediterranean')"))
    op.add_column('entities', sa.Column('potential_strength', sa.Integer(), nullable=True, comment='Innate strength potential (hidden from player)'))
    op.add_column('entities', sa.Column('potential_dexterity', sa.Integer(), nullable=True, comment='Innate dexterity potential (hidden from player)'))
    op.add_column('entities', sa.Column('potential_constitution', sa.Integer(), nullable=True, comment='Innate constitution potential (hidden from player)'))
    op.add_column('entities', sa.Column('potential_intelligence', sa.Integer(), nullable=True, comment='Innate intelligence potential (hidden from player)'))
    op.add_column('entities', sa.Column('potential_wisdom', sa.Integer(), nullable=True, comment='Innate wisdom potential (hidden from player)'))
    op.add_column('entities', sa.Column('potential_charisma', sa.Integer(), nullable=True, comment='Innate charisma potential (hidden from player)'))
    op.add_column('entities', sa.Column('occupation', sa.String(length=100), nullable=True, comment="Primary occupation/profession (e.g., 'blacksmith', 'farmer', 'scholar')"))
    op.add_column('entities', sa.Column('occupation_years', sa.Integer(), nullable=True, comment='Years spent in the occupation (affects attribute modifiers)'))
    op.alter_column('location_visits', 'location_key',
               existing_type=sa.VARCHAR(length=100),
               comment='Key of the visited location',
               existing_nullable=False)
    op.alter_column('location_visits', 'last_visit_turn',
               existing_type=sa.INTEGER(),
               comment='Turn number of the last visit',
               existing_nullable=False)
    op.alter_column('location_visits', 'last_visit_time',
               existing_type=sa.VARCHAR(length=5),
               comment='In-game time of the last visit (HH:MM)',
               existing_nullable=True)
    op.alter_column('location_visits', 'last_visit_day',
               existing_type=sa.INTEGER(),
               comment='In-game day of the last visit',
               existing_nullable=True)
    op.alter_column('location_visits', 'items_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='List of item keys present at last visit',
               existing_nullable=True)
    op.alter_column('location_visits', 'npcs_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='List of NPC entity keys present at last visit',
               existing_nullable=True)
    op.add_column('npc_extensions', sa.Column('is_companion', sa.Boolean(), nullable=False, server_default='false', comment='Whether NPC is currently traveling with player (needs decay tracked)'))
    op.add_column('npc_extensions', sa.Column('companion_since_turn', sa.Integer(), nullable=True, comment='Turn when NPC joined as companion'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npc_extensions', 'companion_since_turn')
    op.drop_column('npc_extensions', 'is_companion')
    op.alter_column('location_visits', 'npcs_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of NPC entity keys present at last visit',
               existing_nullable=True)
    op.alter_column('location_visits', 'items_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of item keys present at last visit',
               existing_nullable=True)
    op.alter_column('location_visits', 'last_visit_day',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='In-game day of the last visit',
               existing_nullable=True)
    op.alter_column('location_visits', 'last_visit_time',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='In-game time of the last visit (HH:MM)',
               existing_nullable=True)
    op.alter_column('location_visits', 'last_visit_turn',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Turn number of the last visit',
               existing_nullable=False)
    op.alter_column('location_visits', 'location_key',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Key of the visited location',
               existing_nullable=False)
    op.drop_column('entities', 'occupation_years')
    op.drop_column('entities', 'occupation')
    op.drop_column('entities', 'potential_charisma')
    op.drop_column('entities', 'potential_wisdom')
    op.drop_column('entities', 'potential_intelligence')
    op.drop_column('entities', 'potential_constitution')
    op.drop_column('entities', 'potential_dexterity')
    op.drop_column('entities', 'potential_strength')
    op.drop_column('entities', 'birthplace')
    op.alter_column('character_needs', 'intimacy',
               existing_type=sa.INTEGER(),
               comment='0=satisfied, 100=desperate. Intimacy need level.',
               existing_comment='0=desperate, 100=content. Intimacy fulfillment level.',
               existing_nullable=False)
    op.alter_column('character_needs', 'wellness',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='0=agony (from injuries), 100=pain-free',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('character_needs', 'energy',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='0=exhausted, 50=tired, 100=energized. Optimal: 60-100',
               existing_nullable=False,
               existing_server_default=sa.text('80'))
    op.drop_column('character_needs', 'last_drink_turn')
    op.drop_column('character_needs', 'intimacy_craving')
    op.drop_column('character_needs', 'social_craving')
    op.drop_column('character_needs', 'energy_craving')
    op.drop_column('character_needs', 'thirst_craving')
    op.drop_column('character_needs', 'hunger_craving')
    op.drop_column('character_needs', 'thirst')
    op.create_table('intimacy_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('drive_level', postgresql.ENUM('asexual', 'very_low', 'low', 'moderate', 'high', 'very_high', name='drivelevel'), autoincrement=False, nullable=False, comment='Affects intimacy need decay rate'),
    sa.Column('drive_threshold', sa.INTEGER(), autoincrement=False, nullable=False, comment='When need triggers behavior (0-100)'),
    sa.Column('intimacy_style', postgresql.ENUM('casual', 'emotional', 'monogamous', 'polyamorous', name='intimacystyle'), autoincrement=False, nullable=False, comment='casual, emotional, monogamous, polyamorous'),
    sa.Column('attraction_preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Preferred traits: {gender: any, age_range: [25,40], traits: [confident, kind]}'),
    sa.Column('has_regular_partner', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_actively_seeking', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name='intimacy_profiles_entity_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name='intimacy_profiles_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='intimacy_profiles_pkey')
    )
    op.create_index('ix_intimacy_profiles_session_id', 'intimacy_profiles', ['session_id'], unique=False)
    op.create_index('ix_intimacy_profiles_id', 'intimacy_profiles', ['id'], unique=False)
    op.create_index('ix_intimacy_profiles_entity_id', 'intimacy_profiles', ['entity_id'], unique=True)
    op.drop_index(op.f('ix_zone_discoveries_zone_id'), table_name='zone_discoveries')
    op.drop_index(op.f('ix_zone_discoveries_session_id'), table_name='zone_discoveries')
    op.drop_index(op.f('ix_zone_discoveries_id'), table_name='zone_discoveries')
    op.drop_table('zone_discoveries')
    op.drop_index(op.f('ix_map_items_session_id'), table_name='map_items')
    op.drop_index(op.f('ix_map_items_item_id'), table_name='map_items')
    op.drop_index(op.f('ix_map_items_id'), table_name='map_items')
    op.drop_table('map_items')
    op.drop_index(op.f('ix_location_discoveries_session_id'), table_name='location_discoveries')
    op.drop_index(op.f('ix_location_discoveries_location_id'), table_name='location_discoveries')
    op.drop_index(op.f('ix_location_discoveries_id'), table_name='location_discoveries')
    op.drop_table('location_discoveries')
    op.drop_index(op.f('ix_zone_connections_to_zone_id'), table_name='zone_connections')
    op.drop_index(op.f('ix_zone_connections_session_id'), table_name='zone_connections')
    op.drop_index(op.f('ix_zone_connections_id'), table_name='zone_connections')
    op.drop_index(op.f('ix_zone_connections_from_zone_id'), table_name='zone_connections')
    op.drop_index('ix_zone_connection_from_passable', table_name='zone_connections')
    op.drop_table('zone_connections')
    op.drop_index(op.f('ix_location_zone_placements_zone_id'), table_name='location_zone_placements')
    op.drop_index(op.f('ix_location_zone_placements_session_id'), table_name='location_zone_placements')
    op.drop_index(op.f('ix_location_zone_placements_location_id'), table_name='location_zone_placements')
    op.drop_index(op.f('ix_location_zone_placements_id'), table_name='location_zone_placements')
    op.drop_table('location_zone_placements')
    op.drop_index(op.f('ix_character_memories_session_id'), table_name='character_memories')
    op.drop_index(op.f('ix_character_memories_id'), table_name='character_memories')
    op.drop_index(op.f('ix_character_memories_entity_id'), table_name='character_memories')
    op.drop_table('character_memories')
    op.drop_index(op.f('ix_terrain_zones_zone_key'), table_name='terrain_zones')
    op.drop_index(op.f('ix_terrain_zones_terrain_type'), table_name='terrain_zones')
    op.drop_index(op.f('ix_terrain_zones_session_id'), table_name='terrain_zones')
    op.drop_index(op.f('ix_terrain_zones_id'), table_name='terrain_zones')
    op.drop_table('terrain_zones')
    op.drop_index(op.f('ix_digital_map_access_session_id'), table_name='digital_map_access')
    op.drop_index(op.f('ix_digital_map_access_service_key'), table_name='digital_map_access')
    op.drop_index(op.f('ix_digital_map_access_id'), table_name='digital_map_access')
    op.drop_table('digital_map_access')
    op.drop_index(op.f('ix_transport_modes_mode_key'), table_name='transport_modes')
    op.drop_index(op.f('ix_transport_modes_id'), table_name='transport_modes')
    op.drop_table('transport_modes')
    # ### end Alembic commands ###
