"""llm_generated_arcs_and_voices

Revision ID: 4fbbe5395f6d
Revises: 111af31a57d1
Create Date: 2025-12-11 18:52:15.669101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fbbe5395f6d'
down_revision: Union[str, None] = '111af31a57d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npc_extensions', sa.Column('voice_template_json', sa.JSON(), nullable=True, comment='LLM-generated voice template with speech patterns, verbal tics, example dialogue'))
    op.alter_column('npc_extensions', 'speech_pattern',
               existing_type=sa.TEXT(),
               comment='How they speak (accent, vocabulary, quirks) - legacy field',
               existing_comment='How they speak (accent, vocabulary, quirks)',
               existing_nullable=True)
    op.add_column('relationship_arcs', sa.Column('arc_template', sa.JSON(), nullable=True, comment='LLM-generated arc template with phases and milestones'))
    op.add_column('relationship_arcs', sa.Column('arc_description', sa.Text(), nullable=True, comment='Description of what this arc represents'))
    op.alter_column('relationship_arcs', 'arc_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('relationship_arcs', 'current_phase',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('relationship_arcs', 'current_phase',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('relationship_arcs', 'arc_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('relationship_arcs', 'arc_description')
    op.drop_column('relationship_arcs', 'arc_template')
    op.alter_column('npc_extensions', 'speech_pattern',
               existing_type=sa.TEXT(),
               comment='How they speak (accent, vocabulary, quirks)',
               existing_comment='How they speak (accent, vocabulary, quirks) - legacy field',
               existing_nullable=True)
    op.drop_column('npc_extensions', 'voice_template_json')
    # ### end Alembic commands ###
