"""add_subturn_metadata_to_turns

Revision ID: 52aef17597f5
Revises: 0ad9be14ad12
Create Date: 2025-12-19 20:10:49.904438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52aef17597f5'
down_revision: Union[str, None] = '0ad9be14ad12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('subturn_metadata', sa.JSON(), nullable=True, comment='[{index, action, execution, complication, state_after}] - subturn details'))
    op.add_column('turns', sa.Column('queued_actions', sa.JSON(), nullable=True, comment='Remaining actions for player choice continuation'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'queued_actions')
    op.drop_column('turns', 'subturn_metadata')
    # ### end Alembic commands ###
