"""add hidden_backstory to entities

Revision ID: 543ae419033d
Revises: 003_preferences
Create Date: 2025-12-07 18:24:54.538303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543ae419033d'
down_revision: Union[str, None] = '003_preferences'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('hidden_backstory', sa.Text(), nullable=True, comment='Secret backstory elements (destiny, hidden powers) - never shown to player'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'hidden_backstory')
    # ### end Alembic commands ###
