"""add_mentioned_npcs_to_turns

Revision ID: 54cbf2dbce3a
Revises: 52aef17597f5
Create Date: 2025-12-19 22:11:29.351041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54cbf2dbce3a'
down_revision: Union[str, None] = '52aef17597f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('mentioned_npcs', sa.JSON(), nullable=True, comment='[{name, description, context, location}] - background NPCs for deferred spawn'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'mentioned_npcs')
    # ### end Alembic commands ###
