"""add relationship_description to relationships

Revision ID: 67612c52485a
Revises: 40abf4bc66f1
Create Date: 2025-12-20 11:01:42.671082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67612c52485a'
down_revision: Union[str, None] = '40abf4bc66f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('needs_communication_log', 'need_name',
               existing_type=sa.VARCHAR(),
               comment='Need being tracked (hunger, stamina, sleep_pressure, hygiene, etc.)',
               existing_comment='Need being tracked (hunger, energy, hygiene, etc.)',
               existing_nullable=False)
    op.add_column('relationships', sa.Column('relationship_description', sa.Text(), nullable=True, comment='Narrative description of current relationship state'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'relationship_description')
    op.alter_column('needs_communication_log', 'need_name',
               existing_type=sa.VARCHAR(),
               comment='Need being tracked (hunger, energy, hygiene, etc.)',
               existing_comment='Need being tracked (hunger, stamina, sleep_pressure, hygiene, etc.)',
               existing_nullable=False)
    # ### end Alembic commands ###
