"""add mentioned_entities column to turns

Revision ID: 6b0862fffd95
Revises: 67612c52485a
Create Date: 2025-12-20 18:14:06.829625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0862fffd95'
down_revision: Union[str, None] = '67612c52485a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('mentioned_entities', sa.JSON(), nullable=True, comment='[{reference_id, display_text, descriptors, gender, group_id, contrast_with, spawned_as}]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'mentioned_entities')
    # ### end Alembic commands ###
