"""add_magic_system_tables

Revision ID: 7247cbddafd1
Revises: d44072093509
Create Date: 2025-12-11 20:59:07.266858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7247cbddafd1'
down_revision: Union[str, None] = 'd44072093509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spell_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('spell_key', sa.String(length=100), nullable=False, comment='Unique spell identifier within session'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment='Human-readable spell name'),
    sa.Column('tradition', sa.String(length=50), nullable=False, comment='Magic tradition: arcane, divine, primal, psionic, occult'),
    sa.Column('school', sa.String(length=50), nullable=False, comment='Spell school: abjuration, conjuration, etc.'),
    sa.Column('level', sa.Integer(), nullable=False, comment='Spell level (0 = cantrip, 1-9 = spell levels)'),
    sa.Column('base_cost', sa.Integer(), nullable=False, comment='Base mana cost to cast'),
    sa.Column('casting_time', sa.String(length=50), nullable=False, comment='Casting time: action, bonus_action, reaction, ritual'),
    sa.Column('range_description', sa.String(length=100), nullable=False, comment='Range: self, touch, 60 feet, etc.'),
    sa.Column('duration', sa.String(length=100), nullable=False, comment='Duration: instantaneous, 1 minute, concentration, etc.'),
    sa.Column('components', sa.JSON(), nullable=False, comment='Required components: verbal, somatic, material'),
    sa.Column('material_component', sa.Text(), nullable=True, comment='Specific material component if required'),
    sa.Column('description', sa.Text(), nullable=False, comment='Full spell description'),
    sa.Column('effects', sa.JSON(), nullable=False, comment='Structured spell effects (damage, healing, conditions, etc.)'),
    sa.Column('scaling', sa.JSON(), nullable=True, comment='How spell scales at higher levels'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Spell templates for the magic system'
    )
    op.create_index(op.f('ix_spell_definitions_id'), 'spell_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_spell_definitions_session_id'), 'spell_definitions', ['session_id'], unique=False)
    op.create_index(op.f('ix_spell_definitions_spell_key'), 'spell_definitions', ['spell_key'], unique=False)
    op.create_table('entity_magic_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('tradition', sa.String(length=50), nullable=True, comment='Primary magic tradition'),
    sa.Column('max_mana', sa.Integer(), nullable=False, comment='Maximum mana pool'),
    sa.Column('current_mana', sa.Integer(), nullable=False, comment='Current mana available'),
    sa.Column('mana_regen_per_rest', sa.Integer(), nullable=False, comment='Mana restored per long rest'),
    sa.Column('known_spells', sa.JSON(), nullable=False, comment='List of spell_keys the entity knows'),
    sa.Column('prepared_spells', sa.JSON(), nullable=True, comment='List of prepared spell_keys (for preparation casters)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Magic capabilities for entities'
    )
    op.create_index(op.f('ix_entity_magic_profiles_entity_id'), 'entity_magic_profiles', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_magic_profiles_id'), 'entity_magic_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_entity_magic_profiles_session_id'), 'entity_magic_profiles', ['session_id'], unique=False)
    op.create_table('spell_cast_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('caster_entity_id', sa.Integer(), nullable=False),
    sa.Column('spell_key', sa.String(length=100), nullable=False, comment='The spell that was cast'),
    sa.Column('turn_cast', sa.Integer(), nullable=False, comment='Game turn when spell was cast'),
    sa.Column('target_entity_keys', sa.JSON(), nullable=False, comment='Entity keys of targets'),
    sa.Column('mana_spent', sa.Integer(), nullable=False, comment='Mana consumed by this cast'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='Whether the spell succeeded'),
    sa.Column('outcome_description', sa.Text(), nullable=True, comment='Description of spell outcome'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caster_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='History of spell casts'
    )
    op.create_index(op.f('ix_spell_cast_records_caster_entity_id'), 'spell_cast_records', ['caster_entity_id'], unique=False)
    op.create_index(op.f('ix_spell_cast_records_id'), 'spell_cast_records', ['id'], unique=False)
    op.create_index(op.f('ix_spell_cast_records_session_id'), 'spell_cast_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_spell_cast_records_spell_key'), 'spell_cast_records', ['spell_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spell_cast_records_spell_key'), table_name='spell_cast_records')
    op.drop_index(op.f('ix_spell_cast_records_session_id'), table_name='spell_cast_records')
    op.drop_index(op.f('ix_spell_cast_records_id'), table_name='spell_cast_records')
    op.drop_index(op.f('ix_spell_cast_records_caster_entity_id'), table_name='spell_cast_records')
    op.drop_table('spell_cast_records')
    op.drop_index(op.f('ix_entity_magic_profiles_session_id'), table_name='entity_magic_profiles')
    op.drop_index(op.f('ix_entity_magic_profiles_id'), table_name='entity_magic_profiles')
    op.drop_index(op.f('ix_entity_magic_profiles_entity_id'), table_name='entity_magic_profiles')
    op.drop_table('entity_magic_profiles')
    op.drop_index(op.f('ix_spell_definitions_spell_key'), table_name='spell_definitions')
    op.drop_index(op.f('ix_spell_definitions_session_id'), table_name='spell_definitions')
    op.drop_index(op.f('ix_spell_definitions_id'), table_name='spell_definitions')
    op.drop_table('spell_definitions')
    # ### end Alembic commands ###
