"""add faction and reputation tables

Revision ID: 76cc10d0166a
Revises: 2564a021f6ff
Create Date: 2025-12-11 15:18:44.367848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cc10d0166a'
down_revision: Union[str, None] = '2564a021f6ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('faction_key', sa.String(length=100), nullable=False, comment='Unique key within session'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Display name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Faction description and background'),
    sa.Column('base_reputation', sa.Integer(), nullable=False, comment='Starting reputation for new entities (-100 to 100)'),
    sa.Column('is_hostile_by_default', sa.Boolean(), nullable=False, comment='If true, faction starts hostile to most entities'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether faction is currently active in the world'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'faction_key', name='uq_faction_key')
    )
    op.create_index(op.f('ix_factions_faction_key'), 'factions', ['faction_key'], unique=False)
    op.create_index(op.f('ix_factions_id'), 'factions', ['id'], unique=False)
    op.create_index(op.f('ix_factions_session_id'), 'factions', ['session_id'], unique=False)
    op.create_table('entity_reputations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=False, comment='Current reputation (-100 to 100)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'faction_id', name='uq_entity_faction_reputation')
    )
    op.create_index(op.f('ix_entity_reputations_entity_id'), 'entity_reputations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_reputations_faction_id'), 'entity_reputations', ['faction_id'], unique=False)
    op.create_index(op.f('ix_entity_reputations_id'), 'entity_reputations', ['id'], unique=False)
    op.create_table('faction_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_faction_id', sa.Integer(), nullable=False),
    sa.Column('to_faction_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False, comment='ally, rival, vassal, overlord, neutral, enemy, etc.'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_faction_id'], ['factions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_faction_id'], ['factions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_faction_id', 'to_faction_id', name='uq_faction_relationship_direction')
    )
    op.create_index(op.f('ix_faction_relationships_from_faction_id'), 'faction_relationships', ['from_faction_id'], unique=False)
    op.create_index(op.f('ix_faction_relationships_id'), 'faction_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_faction_relationships_to_faction_id'), 'faction_relationships', ['to_faction_id'], unique=False)
    op.create_table('reputation_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_reputation_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Integer(), nullable=False),
    sa.Column('new_value', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False, comment='Why this change occurred'),
    sa.Column('turn_number', sa.Integer(), nullable=True, comment='Turn when change occurred'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_reputation_id'], ['entity_reputations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reputation_changes_entity_reputation_id'), 'reputation_changes', ['entity_reputation_id'], unique=False)
    op.create_index(op.f('ix_reputation_changes_id'), 'reputation_changes', ['id'], unique=False)
    op.create_index(op.f('ix_reputation_changes_turn_number'), 'reputation_changes', ['turn_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reputation_changes_turn_number'), table_name='reputation_changes')
    op.drop_index(op.f('ix_reputation_changes_id'), table_name='reputation_changes')
    op.drop_index(op.f('ix_reputation_changes_entity_reputation_id'), table_name='reputation_changes')
    op.drop_table('reputation_changes')
    op.drop_index(op.f('ix_faction_relationships_to_faction_id'), table_name='faction_relationships')
    op.drop_index(op.f('ix_faction_relationships_id'), table_name='faction_relationships')
    op.drop_index(op.f('ix_faction_relationships_from_faction_id'), table_name='faction_relationships')
    op.drop_table('faction_relationships')
    op.drop_index(op.f('ix_entity_reputations_id'), table_name='entity_reputations')
    op.drop_index(op.f('ix_entity_reputations_faction_id'), table_name='entity_reputations')
    op.drop_index(op.f('ix_entity_reputations_entity_id'), table_name='entity_reputations')
    op.drop_table('entity_reputations')
    op.drop_index(op.f('ix_factions_session_id'), table_name='factions')
    op.drop_index(op.f('ix_factions_id'), table_name='factions')
    op.drop_index(op.f('ix_factions_faction_key'), table_name='factions')
    op.drop_table('factions')
    # ### end Alembic commands ###
