"""add_achievement_system

Revision ID: 79d56dc7020f
Revises: efe625b872a5
Create Date: 2025-12-11 15:03:34.473680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d56dc7020f'
down_revision: Union[str, None] = 'efe625b872a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('achievement_key', sa.String(length=100), nullable=False, comment="Unique key within session (e.g., 'first_blood')"),
    sa.Column('title', sa.String(length=200), nullable=False, comment="Display title (e.g., 'First Blood')"),
    sa.Column('description', sa.Text(), nullable=False, comment='Description of how to earn this achievement'),
    sa.Column('achievement_type', sa.Enum('first_discovery', 'milestone', 'title', 'rank', 'secret', name='achievementtype'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False, comment='Achievement points awarded'),
    sa.Column('target_count', sa.Integer(), nullable=True, comment='Target count for progress-based achievements'),
    sa.Column('requirements', sa.JSON(), nullable=True, comment='Requirements to unlock (skill levels, items, etc.)'),
    sa.Column('is_hidden', sa.Boolean(), nullable=False, comment='If true, achievement is hidden until unlocked'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'achievement_key', name='uq_achievement_key')
    )
    op.create_index(op.f('ix_achievements_achievement_key'), 'achievements', ['achievement_key'], unique=False)
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_index(op.f('ix_achievements_session_id'), 'achievements', ['session_id'], unique=False)
    op.create_table('entity_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.Column('unlocked_turn', sa.Integer(), nullable=True, comment='Turn when achievement was unlocked'),
    sa.Column('current_count', sa.Integer(), nullable=False, comment='Current progress toward target'),
    sa.Column('notified', sa.Boolean(), nullable=False, comment='Whether player has been notified of this unlock'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'achievement_id', name='uq_entity_achievement')
    )
    op.create_index(op.f('ix_entity_achievements_achievement_id'), 'entity_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_entity_achievements_entity_id'), 'entity_achievements', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_achievements_id'), 'entity_achievements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_achievements_id'), table_name='entity_achievements')
    op.drop_index(op.f('ix_entity_achievements_entity_id'), table_name='entity_achievements')
    op.drop_index(op.f('ix_entity_achievements_achievement_id'), table_name='entity_achievements')
    op.drop_table('entity_achievements')
    op.drop_index(op.f('ix_achievements_session_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_achievement_key'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
