"""add_destiny_tables

Revision ID: 7deb1bdd87cc
Revises: 7247cbddafd1
Create Date: 2025-12-11 21:03:04.043452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7deb1bdd87cc'
down_revision: Union[str, None] = '7247cbddafd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prophesies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('prophesy_key', sa.String(length=100), nullable=False, comment='Unique prophecy identifier'),
    sa.Column('prophesy_text', sa.Text(), nullable=False, comment='Prophecy text as the player hears it'),
    sa.Column('true_meaning', sa.Text(), nullable=False, comment='GM-only: actual interpretation of the prophecy'),
    sa.Column('source', sa.String(length=100), nullable=False, comment='Source of prophecy: oracle, ancient_tome, dying_seer, etc.'),
    sa.Column('delivered_turn', sa.Integer(), nullable=False, comment='Turn when prophecy was delivered to player'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Prophecy status: active, fulfilled, subverted, abandoned'),
    sa.Column('fulfillment_conditions', sa.JSON(), nullable=False, comment='Conditions that would fulfill this prophecy'),
    sa.Column('subversion_conditions', sa.JSON(), nullable=False, comment='Conditions that would allow avoiding this prophecy'),
    sa.Column('interpretation_hints', sa.JSON(), nullable=False, comment='Clues/hints for player interpretation'),
    sa.Column('fulfilled_turn', sa.Integer(), nullable=True, comment='Turn when prophecy was resolved (fulfilled/subverted)'),
    sa.Column('resolution_description', sa.Text(), nullable=True, comment='Description of how prophecy was resolved'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prophesies_id'), 'prophesies', ['id'], unique=False)
    op.create_index(op.f('ix_prophesies_prophesy_key'), 'prophesies', ['prophesy_key'], unique=False)
    op.create_index(op.f('ix_prophesies_session_id'), 'prophesies', ['session_id'], unique=False)
    op.create_index(op.f('ix_prophesies_status'), 'prophesies', ['status'], unique=False)
    op.create_table('destiny_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('element_key', sa.String(length=100), nullable=False, comment='Unique element identifier'),
    sa.Column('element_type', sa.String(length=20), nullable=False, comment='Element type: omen, sign, portent, vision'),
    sa.Column('description', sa.Text(), nullable=False, comment='Description of the destiny element'),
    sa.Column('prophesy_id', sa.Integer(), nullable=True, comment='Linked prophecy (if any)'),
    sa.Column('witnessed_by', sa.JSON(), nullable=False, comment='Entity keys of those who witnessed this element'),
    sa.Column('turn_occurred', sa.Integer(), nullable=False, comment='Turn when element occurred'),
    sa.Column('significance', sa.Integer(), nullable=False, comment='Significance level 1-5 (5 = most significant)'),
    sa.Column('player_noticed', sa.Boolean(), nullable=False, comment='Whether player explicitly noticed this element'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prophesy_id'], ['prophesies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destiny_elements_element_key'), 'destiny_elements', ['element_key'], unique=False)
    op.create_index(op.f('ix_destiny_elements_id'), 'destiny_elements', ['id'], unique=False)
    op.create_index(op.f('ix_destiny_elements_prophesy_id'), 'destiny_elements', ['prophesy_id'], unique=False)
    op.create_index(op.f('ix_destiny_elements_session_id'), 'destiny_elements', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_destiny_elements_session_id'), table_name='destiny_elements')
    op.drop_index(op.f('ix_destiny_elements_prophesy_id'), table_name='destiny_elements')
    op.drop_index(op.f('ix_destiny_elements_id'), table_name='destiny_elements')
    op.drop_index(op.f('ix_destiny_elements_element_key'), table_name='destiny_elements')
    op.drop_table('destiny_elements')
    op.drop_index(op.f('ix_prophesies_status'), table_name='prophesies')
    op.drop_index(op.f('ix_prophesies_session_id'), table_name='prophesies')
    op.drop_index(op.f('ix_prophesies_prophesy_key'), table_name='prophesies')
    op.drop_index(op.f('ix_prophesies_id'), table_name='prophesies')
    op.drop_table('prophesies')
    # ### end Alembic commands ###
