"""add is_ooc to turns

Revision ID: 858b279a2ac6
Revises: 6b0862fffd95
Create Date: 2025-12-22 08:06:25.439473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858b279a2ac6'
down_revision: Union[str, None] = '6b0862fffd95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('is_ooc', sa.Boolean(), nullable=False, server_default='false', comment='True if this is an out-of-character response (meta/lore question)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'is_ooc')
    # ### end Alembic commands ###
