"""add_session_snapshots

Revision ID: 8c46f05ac0b1
Revises: 54cbf2dbce3a
Create Date: 2025-12-20 07:13:46.027961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c46f05ac0b1'
down_revision: Union[str, None] = '54cbf2dbce3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=False, comment='Complete session state as JSON'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_snapshots_id'), 'session_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_session_snapshots_session_id'), 'session_snapshots', ['session_id'], unique=False)
    op.create_index('ix_session_snapshots_session_turn', 'session_snapshots', ['session_id', 'turn_number'], unique=True)
    op.create_index(op.f('ix_session_snapshots_turn_number'), 'session_snapshots', ['turn_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_snapshots_turn_number'), table_name='session_snapshots')
    op.drop_index('ix_session_snapshots_session_turn', table_name='session_snapshots')
    op.drop_index(op.f('ix_session_snapshots_session_id'), table_name='session_snapshots')
    op.drop_index(op.f('ix_session_snapshots_id'), table_name='session_snapshots')
    op.drop_table('session_snapshots')
    # ### end Alembic commands ###
