"""add_entity_temporary_state

Revision ID: 90c258815db1
Revises: 929cfa212ff9
Create Date: 2025-12-18 09:37:38.832726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c258815db1'
down_revision: Union[str, None] = '929cfa212ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('temporary_state', sa.JSON(), nullable=True, comment='Transient entity state (posture, position, temporary conditions)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'temporary_state')
    # ### end Alembic commands ###
