"""add_context_summary_models

Revision ID: 929cfa212ff9
Revises: fe9bcef406ba
Create Date: 2025-12-17 16:53:36.920354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '929cfa212ff9'
down_revision: Union[str, None] = 'fe9bcef406ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('milestone_type', sa.Enum('arc_phase_change', 'quest_complete', 'mystery_solved', 'major_relationship', 'region_transition', 'conflict_resolution', 'major_discovery', 'character_development', name='milestonetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False, comment='Brief description of what happened at this milestone'),
    sa.Column('turn_number', sa.Integer(), nullable=False, comment='Turn number when milestone occurred'),
    sa.Column('game_day', sa.Integer(), nullable=False, comment='In-game day when milestone occurred'),
    sa.Column('game_time', sa.String(length=5), nullable=True, comment='In-game time (HH:MM) when milestone occurred'),
    sa.Column('related_entity_key', sa.String(length=100), nullable=True, comment='Key of related entity (quest_key, arc_key, etc.)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_id'), 'milestones', ['id'], unique=False)
    op.create_index(op.f('ix_milestones_session_id'), 'milestones', ['session_id'], unique=False)
    op.create_index(op.f('ix_milestones_turn_number'), 'milestones', ['turn_number'], unique=False)
    op.create_table('narrative_mention_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('mention_type', sa.String(length=50), nullable=False, comment='Type of mention: need_state, injury, equipment, relationship, etc.'),
    sa.Column('subject_key', sa.String(length=100), nullable=False, comment='Subject of mention: entity_key, need_name, item_key, etc.'),
    sa.Column('mention_value', sa.String(length=200), nullable=False, comment="The specific value/state mentioned: 'disheveled', 'tired', etc."),
    sa.Column('mentioned_turn', sa.Integer(), nullable=False, comment='Turn number when this was mentioned'),
    sa.Column('mentioned_game_time', sa.DateTime(), nullable=False, comment='In-game datetime when this was mentioned'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'mention_type', 'subject_key', name='uq_narrative_mention_session_type_subject')
    )
    op.create_index(op.f('ix_narrative_mention_log_id'), 'narrative_mention_log', ['id'], unique=False)
    op.create_index(op.f('ix_narrative_mention_log_mentioned_turn'), 'narrative_mention_log', ['mentioned_turn'], unique=False)
    op.create_index(op.f('ix_narrative_mention_log_session_id'), 'narrative_mention_log', ['session_id'], unique=False)
    op.create_table('context_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('summary_type', sa.Enum('story', 'recent', name='summarytype'), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False, comment='The generated summary text'),
    sa.Column('generated_at_turn', sa.Integer(), nullable=False, comment='Turn when this summary was generated'),
    sa.Column('generated_at_day', sa.Integer(), nullable=False, comment='In-game day when this summary was generated'),
    sa.Column('covers_through_turn', sa.Integer(), nullable=False, comment='Last turn number included in this summary'),
    sa.Column('covers_through_day', sa.Integer(), nullable=False, comment='Last in-game day included in this summary'),
    sa.Column('milestone_id', sa.Integer(), nullable=True, comment='Last milestone covered by this summary'),
    sa.Column('key_characters', sa.JSON(), nullable=True, comment='Key characters mentioned in summary'),
    sa.Column('key_decisions', sa.JSON(), nullable=True, comment='Key player decisions captured'),
    sa.Column('current_objectives', sa.JSON(), nullable=True, comment='Current active objectives/quests'),
    sa.Column('token_count', sa.Integer(), nullable=False, comment='Approximate token count of summary'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'summary_type', name='uq_context_summary_session_type')
    )
    op.create_index(op.f('ix_context_summaries_id'), 'context_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_context_summaries_session_id'), 'context_summaries', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_context_summaries_session_id'), table_name='context_summaries')
    op.drop_index(op.f('ix_context_summaries_id'), table_name='context_summaries')
    op.drop_table('context_summaries')
    op.drop_index(op.f('ix_narrative_mention_log_session_id'), table_name='narrative_mention_log')
    op.drop_index(op.f('ix_narrative_mention_log_mentioned_turn'), table_name='narrative_mention_log')
    op.drop_index(op.f('ix_narrative_mention_log_id'), table_name='narrative_mention_log')
    op.drop_table('narrative_mention_log')
    op.drop_index(op.f('ix_milestones_turn_number'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_session_id'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_id'), table_name='milestones')
    op.drop_table('milestones')
    # ### end Alembic commands ###
