"""add entity conditions table

Revision ID: a3c9cc28fc46
Revises: ec5a9e5f55d4
Create Date: 2025-12-11 15:33:21.556936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c9cc28fc46'
down_revision: Union[str, None] = 'ec5a9e5f55d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('prone', 'grappled', 'restrained', 'paralyzed', 'blinded', 'deafened', 'invisible', 'stunned', 'incapacitated', 'unconscious', 'poisoned', 'frightened', 'charmed', 'exhausted', 'concentrating', 'petrified', 'hidden', name='combatcondition'), nullable=False),
    sa.Column('duration_rounds', sa.Integer(), nullable=True, comment='Total duration in rounds (null = permanent)'),
    sa.Column('rounds_remaining', sa.Integer(), nullable=True, comment='Rounds left (decremented each turn)'),
    sa.Column('source_entity_id', sa.Integer(), nullable=True, comment='Entity that caused this condition'),
    sa.Column('source_description', sa.String(length=200), nullable=True, comment="Description of source (e.g., 'Ghoul's Paralysis')"),
    sa.Column('exhaustion_level', sa.Integer(), nullable=True, comment='For exhaustion: level 1-6'),
    sa.Column('applied_turn', sa.Integer(), nullable=True, comment='Turn number when applied'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'condition', name='uq_entity_condition')
    )
    op.create_index(op.f('ix_entity_conditions_entity_id'), 'entity_conditions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_conditions_id'), 'entity_conditions', ['id'], unique=False)
    op.create_index(op.f('ix_entity_conditions_session_id'), 'entity_conditions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_conditions_session_id'), table_name='entity_conditions')
    op.drop_index(op.f('ix_entity_conditions_id'), table_name='entity_conditions')
    op.drop_index(op.f('ix_entity_conditions_entity_id'), table_name='entity_conditions')
    op.drop_table('entity_conditions')
    # ### end Alembic commands ###
