"""add needs_communication_log table

Revision ID: b58577444302
Revises: 25d0fb8756ad
Create Date: 2025-12-15 08:19:26.819372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58577444302'
down_revision: Union[str, None] = '25d0fb8756ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('needs_communication_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('need_name', sa.String(), nullable=False, comment='Need being tracked (hunger, energy, hygiene, etc.)'),
    sa.Column('communicated_turn', sa.Integer(), nullable=False, comment='Turn number when this need was last narrated'),
    sa.Column('communicated_game_time', sa.DateTime(), nullable=False, comment='In-game datetime when this need was last narrated'),
    sa.Column('communicated_value', sa.Integer(), nullable=False, comment='Need value (0-100) at time of communication'),
    sa.Column('communicated_state', sa.String(), nullable=False, comment='State label (hungry, starving, well-fed, etc.) when communicated'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'entity_id', 'need_name', name='uq_needs_comm_session_entity_need')
    )
    op.create_index(op.f('ix_needs_communication_log_entity_id'), 'needs_communication_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_needs_communication_log_id'), 'needs_communication_log', ['id'], unique=False)
    op.create_index(op.f('ix_needs_communication_log_session_id'), 'needs_communication_log', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_needs_communication_log_session_id'), table_name='needs_communication_log')
    op.drop_index(op.f('ix_needs_communication_log_id'), table_name='needs_communication_log')
    op.drop_index(op.f('ix_needs_communication_log_entity_id'), table_name='needs_communication_log')
    op.drop_table('needs_communication_log')
    # ### end Alembic commands ###
