"""add narrative models story_arc mystery conflict

Revision ID: c570e2f1f0dd
Revises: 369661c753f3
Create Date: 2025-12-11 14:38:59.103238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c570e2f1f0dd'
down_revision: Union[str, None] = '369661c753f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_arcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('arc_key', sa.String(length=100), nullable=False, comment="Unique key (e.g., 'main_quest', 'romance_elara')"),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Human-readable title'),
    sa.Column('arc_type', sa.Enum('main_quest', 'side_quest', 'romance', 'revenge', 'redemption', 'mystery', 'rivalry', 'mentorship', 'betrayal', 'survival', 'discovery', 'political', name='arctype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True, comment='Overview of the arc'),
    sa.Column('status', sa.Enum('dormant', 'active', 'paused', 'completed', 'failed', 'abandoned', name='arcstatus'), nullable=False),
    sa.Column('current_phase', sa.Enum('setup', 'rising_action', 'midpoint', 'escalation', 'climax', 'falling_action', 'resolution', 'aftermath', name='arcphase'), nullable=False),
    sa.Column('tension_level', sa.Integer(), nullable=False, comment='Current tension 0-100'),
    sa.Column('phase_started_turn', sa.Integer(), nullable=True, comment='Turn when current phase began'),
    sa.Column('turns_in_phase', sa.Integer(), nullable=False, comment='Turns spent in current phase'),
    sa.Column('planted_elements', sa.JSON(), nullable=True, comment="Chekhov's guns - elements that must pay off"),
    sa.Column('resolved_elements', sa.JSON(), nullable=True, comment='Elements that have paid off'),
    sa.Column('next_beat_hint', sa.Text(), nullable=True, comment='Suggestion for next narrative beat'),
    sa.Column('stakes', sa.Text(), nullable=True, comment="What's at stake in this arc"),
    sa.Column('protagonist_id', sa.Integer(), nullable=True, comment='Main character driving this arc'),
    sa.Column('antagonist_id', sa.Integer(), nullable=True, comment='Opposing force in this arc'),
    sa.Column('started_turn', sa.Integer(), nullable=True, comment='Turn when arc became active'),
    sa.Column('completed_turn', sa.Integer(), nullable=True, comment='Turn when arc completed'),
    sa.Column('outcome', sa.Text(), nullable=True, comment='How the arc resolved'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='1-10, higher = more important'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['antagonist_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['protagonist_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_arcs_arc_key'), 'story_arcs', ['arc_key'], unique=False)
    op.create_index(op.f('ix_story_arcs_id'), 'story_arcs', ['id'], unique=False)
    op.create_index(op.f('ix_story_arcs_session_id'), 'story_arcs', ['session_id'], unique=False)
    op.create_table('conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('conflict_key', sa.String(length=100), nullable=False, comment="Unique key (e.g., 'guild_war', 'family_feud')"),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('party_a_key', sa.String(length=100), nullable=True, comment='Entity/faction key for first party'),
    sa.Column('party_b_key', sa.String(length=100), nullable=True, comment='Entity/faction key for second party'),
    sa.Column('current_level', sa.Enum('tension', 'dispute', 'confrontation', 'hostility', 'crisis', 'war', name='conflictlevel'), nullable=False),
    sa.Column('level_numeric', sa.Integer(), nullable=False, comment='Numeric level 1-6 for comparison'),
    sa.Column('escalation_triggers', sa.JSON(), nullable=True, comment='Conditions that escalate conflict'),
    sa.Column('de_escalation_triggers', sa.JSON(), nullable=True, comment='Conditions that reduce tension'),
    sa.Column('level_descriptions', sa.JSON(), nullable=True, comment='Description of what each level looks like'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True, comment='How conflict was resolved'),
    sa.Column('started_turn', sa.Integer(), nullable=False),
    sa.Column('last_escalation_turn', sa.Integer(), nullable=True),
    sa.Column('resolved_turn', sa.Integer(), nullable=True),
    sa.Column('story_arc_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_arc_id'], ['story_arcs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflicts_conflict_key'), 'conflicts', ['conflict_key'], unique=False)
    op.create_index(op.f('ix_conflicts_id'), 'conflicts', ['id'], unique=False)
    op.create_index(op.f('ix_conflicts_session_id'), 'conflicts', ['session_id'], unique=False)
    op.create_table('mysteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('mystery_key', sa.String(length=100), nullable=False, comment="Unique key (e.g., 'who_killed_mayor')"),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Human-readable title'),
    sa.Column('truth', sa.Text(), nullable=False, comment='What actually happened (GM only)'),
    sa.Column('truth_summary', sa.String(length=500), nullable=True, comment='Short summary for context'),
    sa.Column('clues', sa.JSON(), nullable=True, comment='List of clue objects with discovery status'),
    sa.Column('red_herrings', sa.JSON(), nullable=True, comment='False leads to consider'),
    sa.Column('clues_discovered', sa.Integer(), nullable=False, comment='Number of clues found'),
    sa.Column('total_clues', sa.Integer(), nullable=False, comment='Total clues available'),
    sa.Column('revelation_conditions', sa.Text(), nullable=True, comment='What must happen for truth to be revealed'),
    sa.Column('is_solved', sa.Boolean(), nullable=False),
    sa.Column('solved_turn', sa.Integer(), nullable=True),
    sa.Column('player_theory', sa.Text(), nullable=True, comment='What the player currently believes'),
    sa.Column('story_arc_id', sa.Integer(), nullable=True),
    sa.Column('created_turn', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_arc_id'], ['story_arcs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mysteries_id'), 'mysteries', ['id'], unique=False)
    op.create_index(op.f('ix_mysteries_mystery_key'), 'mysteries', ['mystery_key'], unique=False)
    op.create_index(op.f('ix_mysteries_session_id'), 'mysteries', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mysteries_session_id'), table_name='mysteries')
    op.drop_index(op.f('ix_mysteries_mystery_key'), table_name='mysteries')
    op.drop_index(op.f('ix_mysteries_id'), table_name='mysteries')
    op.drop_table('mysteries')
    op.drop_index(op.f('ix_conflicts_session_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_conflict_key'), table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index(op.f('ix_story_arcs_session_id'), table_name='story_arcs')
    op.drop_index(op.f('ix_story_arcs_id'), table_name='story_arcs')
    op.drop_index(op.f('ix_story_arcs_arc_key'), table_name='story_arcs')
    op.drop_table('story_arcs')
    # ### end Alembic commands ###
