"""add_economy_tables

Revision ID: d44072093509
Revises: 12d9e2934e02
Create Date: 2025-12-11 20:51:28.428369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44072093509'
down_revision: Union[str, None] = '12d9e2934e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=100), nullable=False, comment='Unique event identifier'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='Event type: famine, war, festival, plague, discovery, etc.'),
    sa.Column('description', sa.Text(), nullable=False, comment='Human-readable event description'),
    sa.Column('affected_locations', sa.JSON(), nullable=False, comment='Location keys affected by this event'),
    sa.Column('affected_categories', sa.JSON(), nullable=False, comment='Item categories affected (empty = all categories)'),
    sa.Column('price_modifier', sa.Float(), nullable=False, comment='Price multiplier (0.5 = half, 2.0 = double)'),
    sa.Column('supply_effect', sa.String(length=20), nullable=True, comment="Supply change: 'increase', 'decrease', or null"),
    sa.Column('start_turn', sa.Integer(), nullable=False, comment='Turn when event started'),
    sa.Column('duration_turns', sa.Integer(), nullable=True, comment='Duration in turns (null = permanent)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'event_key', name='uq_economic_event_key')
    )
    op.create_index(op.f('ix_economic_events_event_key'), 'economic_events', ['event_key'], unique=False)
    op.create_index(op.f('ix_economic_events_event_type'), 'economic_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_economic_events_id'), 'economic_events', ['id'], unique=False)
    op.create_index(op.f('ix_economic_events_session_id'), 'economic_events', ['session_id'], unique=False)
    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('location_key', sa.String(length=100), nullable=False, comment='Location key where this market exists'),
    sa.Column('item_category', sa.String(length=50), nullable=False, comment='Item category: weapons, armor, food, luxury, tools, materials, etc.'),
    sa.Column('base_price_modifier', sa.Float(), nullable=False, comment='Location-specific base price modifier (e.g., 1.2 for expensive city)'),
    sa.Column('supply_level', sa.String(length=20), nullable=False, comment='Current supply level'),
    sa.Column('demand_level', sa.String(length=20), nullable=False, comment='Current demand level'),
    sa.Column('last_updated_turn', sa.Integer(), nullable=False, comment='Turn when prices were last recalculated'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'location_key', 'item_category', name='uq_market_location_category')
    )
    op.create_index(op.f('ix_market_prices_id'), 'market_prices', ['id'], unique=False)
    op.create_index(op.f('ix_market_prices_item_category'), 'market_prices', ['item_category'], unique=False)
    op.create_index(op.f('ix_market_prices_location_key'), 'market_prices', ['location_key'], unique=False)
    op.create_index(op.f('ix_market_prices_session_id'), 'market_prices', ['session_id'], unique=False)
    op.create_table('trade_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('route_key', sa.String(length=100), nullable=False, comment='Unique route identifier'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment='Human-readable route name'),
    sa.Column('origin_key', sa.String(length=100), nullable=False, comment='Starting location key'),
    sa.Column('destination_key', sa.String(length=100), nullable=False, comment='Ending location key'),
    sa.Column('goods_traded', sa.JSON(), nullable=False, comment='Item categories traded on this route'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('disruption_reason', sa.Text(), nullable=True, comment='Why route is disrupted/blocked'),
    sa.Column('travel_days', sa.Integer(), nullable=False, comment='Normal travel time in days'),
    sa.Column('danger_level', sa.Integer(), nullable=False, comment='Danger level 0-100 (affects merchant willingness)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'route_key', name='uq_trade_route_key')
    )
    op.create_index(op.f('ix_trade_routes_destination_key'), 'trade_routes', ['destination_key'], unique=False)
    op.create_index(op.f('ix_trade_routes_id'), 'trade_routes', ['id'], unique=False)
    op.create_index(op.f('ix_trade_routes_origin_key'), 'trade_routes', ['origin_key'], unique=False)
    op.create_index(op.f('ix_trade_routes_route_key'), 'trade_routes', ['route_key'], unique=False)
    op.create_index(op.f('ix_trade_routes_session_id'), 'trade_routes', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_routes_session_id'), table_name='trade_routes')
    op.drop_index(op.f('ix_trade_routes_route_key'), table_name='trade_routes')
    op.drop_index(op.f('ix_trade_routes_origin_key'), table_name='trade_routes')
    op.drop_index(op.f('ix_trade_routes_id'), table_name='trade_routes')
    op.drop_index(op.f('ix_trade_routes_destination_key'), table_name='trade_routes')
    op.drop_table('trade_routes')
    op.drop_index(op.f('ix_market_prices_session_id'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_location_key'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_item_category'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_id'), table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index(op.f('ix_economic_events_session_id'), table_name='economic_events')
    op.drop_index(op.f('ix_economic_events_id'), table_name='economic_events')
    op.drop_index(op.f('ix_economic_events_event_type'), table_name='economic_events')
    op.drop_index(op.f('ix_economic_events_event_key'), table_name='economic_events')
    op.drop_table('economic_events')
    # ### end Alembic commands ###
