"""add npc secrets system fields

Revision ID: e28e2ef1e2bf
Revises: c570e2f1f0dd
Create Date: 2025-12-11 14:48:42.351772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28e2ef1e2bf'
down_revision: Union[str, None] = 'c570e2f1f0dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npc_extensions', sa.Column('dark_secret', sa.Text(), nullable=True, comment='Something the NPC is hiding (past crime, forbidden love, true identity)'))
    op.add_column('npc_extensions', sa.Column('hidden_goal', sa.Text(), nullable=True, comment='What the NPC truly wants (may differ from stated goals)'))
    op.add_column('npc_extensions', sa.Column('betrayal_conditions', sa.Text(), nullable=True, comment='Conditions that would cause NPC to betray player'))
    op.add_column('npc_extensions', sa.Column('secret_revealed', sa.Boolean(), nullable=False, comment='Whether dark_secret has been revealed to player'))
    op.add_column('npc_extensions', sa.Column('secret_revealed_turn', sa.Integer(), nullable=True, comment='Turn when secret was revealed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npc_extensions', 'secret_revealed_turn')
    op.drop_column('npc_extensions', 'secret_revealed')
    op.drop_column('npc_extensions', 'betrayal_conditions')
    op.drop_column('npc_extensions', 'hidden_goal')
    op.drop_column('npc_extensions', 'dark_secret')
    # ### end Alembic commands ###
