"""add weapon and armor definition tables

Revision ID: ec5a9e5f55d4
Revises: 76cc10d0166a
Create Date: 2025-12-11 15:28:10.988176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec5a9e5f55d4'
down_revision: Union[str, None] = '76cc10d0166a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('armor_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('armor_key', sa.String(length=100), nullable=False, comment="Unique key within session (e.g., 'leather', 'chainmail')"),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Display name'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('light', 'medium', 'heavy', 'shield', name='armorcategory'), nullable=False),
    sa.Column('base_ac', sa.Integer(), nullable=False, comment='Base AC (or AC bonus for shields)'),
    sa.Column('max_dex_bonus', sa.Integer(), nullable=True, comment='Maximum DEX bonus to AC (None = unlimited, 0 = none)'),
    sa.Column('strength_required', sa.Integer(), nullable=True, comment='Minimum STR to wear without speed penalty'),
    sa.Column('stealth_disadvantage', sa.Boolean(), nullable=False, comment='Disadvantage on stealth checks'),
    sa.Column('weight', sa.Float(), nullable=True, comment='Weight in pounds'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'armor_key', name='uq_armor_definition_key')
    )
    op.create_index(op.f('ix_armor_definitions_armor_key'), 'armor_definitions', ['armor_key'], unique=False)
    op.create_index(op.f('ix_armor_definitions_id'), 'armor_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_armor_definitions_session_id'), 'armor_definitions', ['session_id'], unique=False)
    op.create_table('weapon_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('weapon_key', sa.String(length=100), nullable=False, comment="Unique key within session (e.g., 'longsword', 'shortbow')"),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Display name'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('simple_melee', 'simple_ranged', 'martial_melee', 'martial_ranged', 'exotic', 'improvised', 'natural', name='weaponcategory'), nullable=False),
    sa.Column('damage_dice', sa.String(length=20), nullable=False, comment="Damage dice notation (e.g., '1d8', '2d6')"),
    sa.Column('damage_type', sa.Enum('slashing', 'piercing', 'bludgeoning', 'fire', 'cold', 'lightning', 'acid', 'poison', 'psychic', 'radiant', 'necrotic', 'force', 'thunder', name='damagetype'), nullable=False),
    sa.Column('versatile_dice', sa.String(length=20), nullable=True, comment='Damage dice when used two-handed (for versatile weapons)'),
    sa.Column('properties', sa.JSON(), nullable=True, comment='List of weapon property values (use WeaponProperty.value)'),
    sa.Column('range_type', sa.Enum('melee', 'reach', 'ranged', 'thrown', name='weaponrange'), nullable=False),
    sa.Column('range_normal', sa.Integer(), nullable=True, comment='Normal range in feet (for ranged/thrown)'),
    sa.Column('range_long', sa.Integer(), nullable=True, comment='Long range in feet (disadvantage beyond normal)'),
    sa.Column('weight', sa.Float(), nullable=True, comment='Weight in pounds'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'weapon_key', name='uq_weapon_definition_key')
    )
    op.create_index(op.f('ix_weapon_definitions_id'), 'weapon_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_weapon_definitions_session_id'), 'weapon_definitions', ['session_id'], unique=False)
    op.create_index(op.f('ix_weapon_definitions_weapon_key'), 'weapon_definitions', ['weapon_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weapon_definitions_weapon_key'), table_name='weapon_definitions')
    op.drop_index(op.f('ix_weapon_definitions_session_id'), table_name='weapon_definitions')
    op.drop_index(op.f('ix_weapon_definitions_id'), table_name='weapon_definitions')
    op.drop_table('weapon_definitions')
    op.drop_index(op.f('ix_armor_definitions_session_id'), table_name='armor_definitions')
    op.drop_index(op.f('ix_armor_definitions_id'), table_name='armor_definitions')
    op.drop_index(op.f('ix_armor_definitions_armor_key'), table_name='armor_definitions')
    op.drop_table('armor_definitions')
    # ### end Alembic commands ###
