"""add_skill_usage_tracking

Revision ID: efe625b872a5
Revises: e28e2ef1e2bf
Create Date: 2025-12-11 14:59:36.806951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe625b872a5'
down_revision: Union[str, None] = 'e28e2ef1e2bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add server_default='0' to handle existing rows, then remove it
    op.add_column('entity_skills', sa.Column('usage_count', sa.Integer(), nullable=False, server_default='0', comment='Total times this skill has been used'))
    op.add_column('entity_skills', sa.Column('successful_uses', sa.Integer(), nullable=False, server_default='0', comment='Times skill was used successfully (for advancement)'))

    # Remove server defaults (we want the model default to handle new rows)
    op.alter_column('entity_skills', 'usage_count', server_default=None)
    op.alter_column('entity_skills', 'successful_uses', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_skills', 'successful_uses')
    op.drop_column('entity_skills', 'usage_count')
    # ### end Alembic commands ###
