"""add complication history table

Revision ID: fe9bcef406ba
Revises: b58577444302
Create Date: 2025-12-16 23:00:08.424338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9bcef406ba'
down_revision: Union[str, None] = 'b58577444302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complication_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False, comment='Turn when complication occurred'),
    sa.Column('complication_type', sa.Enum('discovery', 'interruption', 'cost', 'twist', name='complicationtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False, comment='Description of the complication'),
    sa.Column('mechanical_effects', sa.JSON(), nullable=True, comment='Mechanical effects applied'),
    sa.Column('new_facts', sa.JSON(), nullable=True, comment='Facts recorded from this complication'),
    sa.Column('trigger_probability', sa.Float(), nullable=True, comment='Probability that triggered this complication'),
    sa.Column('risk_tags', sa.JSON(), nullable=True, comment='Risk tags that contributed'),
    sa.Column('story_arc_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_arc_id'], ['story_arcs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complication_history_id'), 'complication_history', ['id'], unique=False)
    op.create_index(op.f('ix_complication_history_session_id'), 'complication_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_complication_history_turn_number'), 'complication_history', ['turn_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complication_history_turn_number'), table_name='complication_history')
    op.drop_index(op.f('ix_complication_history_session_id'), table_name='complication_history')
    op.drop_index(op.f('ix_complication_history_id'), table_name='complication_history')
    op.drop_table('complication_history')
    # ### end Alembic commands ###
