"""Database package."""

from src.database.connection import get_db_session, init_db
from src.database.models import (
    Appointment,
    AppointmentStatus,
    Base,
    DayOfWeek,
    Entity,
    EntityAttribute,
    EntitySkill,
    EntityType,
    Fact,
    FactCategory,
    GameSession,
    Item,
    ItemCondition,
    ItemType,
    Location,
    MonsterExtension,
    NPCExtension,
    Quest,
    QuestStage,
    QuestStatus,
    Relationship,
    RelationshipChange,
    Schedule,
    StorageLocation,
    StorageLocationType,
    Task,
    TaskCategory,
    TimeState,
    Turn,
    WorldEvent,
)

__all__ = [
    # Connection
    "get_db_session",
    "init_db",
    # Base
    "Base",
    # Enums
    "EntityType",
    "ItemType",
    "ItemCondition",
    "StorageLocationType",
    "TaskCategory",
    "AppointmentStatus",
    "QuestStatus",
    "DayOfWeek",
    "FactCategory",
    # Models
    "GameSession",
    "Turn",
    "Entity",
    "EntityAttribute",
    "EntitySkill",
    "NPCExtension",
    "MonsterExtension",
    "Item",
    "StorageLocation",
    "Location",
    "Schedule",
    "TimeState",
    "Fact",
    "WorldEvent",
    "Relationship",
    "RelationshipChange",
    "Task",
    "Appointment",
    "Quest",
    "QuestStage",
]
